id = "nightcall-theme"
name = "Nightcall"
version = "0.0.1"
schema_version = 1
authors = ["Robert Patterson"]
description = "Nightcall color themes for Zed"
repository = "https://github.com/bpat86/nightcall-vscode-theme"