const chroma = require("chroma-js");

function alpha(value, percentage) {
  if (!Number.isFinite(percentage) || percentage < 0 || percentage > 100) {
    throw new RangeError("Alpha percentage must be between 0 and 100");
  }

  return chroma(value)
    .alpha(percentage / 100)
    .hex();
}

// These paired guide states use a deliberate, stable contrast relationship.
const BRACKET_GUIDE_ACTIVE_ALPHA = 75;
const BRACKET_GUIDE_INACTIVE_ALPHA = 60;
// Keep resting overlays quieter than engaged states such as hover and matches.
const OVERLAY_RESTING_ALPHA = 50;
const OVERLAY_ENGAGED_ALPHA = 55;

function createWorkbenchColors(color) {
  return {
    // Base text and links
    focusBorder: color.accent.emphasis,
    foreground: color.foreground.default,
    disabledForeground: alpha(color.foreground.subtle, 75),
    descriptionForeground: color.foreground.muted,
    errorForeground: color.danger.foreground,
    "textLink.foreground": color.accent.foreground,
    "textLink.activeForeground": color.accent.foreground,
    "textBlockQuote.background": color.canvas.inset,
    "textBlockQuote.border": alpha(color.accent.tertiary, 50),
    "textCodeBlock.background": color.canvas.default,
    "textPreformat.foreground": color.accent.tertiary,
    "textPreformat.background": color.canvas.default,
    "textSeparator.foreground": color.foreground.default,
    "icon.foreground": color.foreground.muted,
    "keybindingLabel.foreground": color.foreground.default,

    // Buttons, inputs, and controls
    "button.background": color.control.primary.background,
    "button.foreground": color.control.primary.foreground,
    "button.border": color.control.primary.border,
    "button.separator": color.border.muted,
    "button.hoverBackground": color.control.primary.hoverBackground,
    "button.secondaryBackground": color.control.secondary.background,
    "button.secondaryForeground": color.control.secondary.foreground,
    "button.secondaryBorder": color.control.secondary.border,
    "button.secondaryHoverBackground": color.control.secondary.hoverBackground,
    "checkbox.background": color.canvas.overlay,
    "checkbox.border": color.border.emphasis,
    "checkbox.foreground": color.foreground.default,
    "checkbox.selectBackground": color.canvas.overlay,
    "checkbox.selectBorder": color.border.emphasis,
    "checkbox.disabled.background": color.canvas.overlay,
    "checkbox.disabled.foreground": color.foreground.default,
    "dropdown.background": color.control.secondary.background,
    "dropdown.border": color.border.muted,
    "dropdown.foreground": color.foreground.emphasis,
    "dropdown.listBackground": color.control.secondary.background,
    "radio.activeForeground": color.foreground.default,
    "radio.activeBackground": color.canvas.overlay,
    "radio.activeBorder": color.border.emphasis,
    "radio.inactiveForeground": color.foreground.muted,
    "radio.inactiveBackground": color.canvas.overlay,
    "radio.inactiveBorder": color.border.emphasis,
    "radio.inactiveHoverBackground": color.canvas.overlay,
    "sash.hoverBorder": color.control.secondary.background,
    "input.background": color.canvas.default,
    "input.border": color.border.default,
    "input.foreground": color.foreground.emphasis,
    "input.placeholderForeground": color.foreground.muted,
    "badge.foreground": color.foreground.muted,
    "badge.background": color.canvas.inset,
    "progressBar.background": color.accent.foreground,
    "extensionButton.prominentBackground": color.control.primary.background,
    "extensionButton.prominentForeground": color.control.primary.foreground,
    "extensionButton.prominentHoverBackground":
      color.control.primary.hoverBackground,
    "extensionButton.background": color.control.secondary.background,
    "extensionButton.foreground": color.control.secondary.foreground,
    "extensionButton.hoverBackground": color.control.secondary.hoverBackground,
    "extensionButton.separator": color.border.muted,
    "extensionButton.border": color.border.default,
    "extensionBadge.remoteBackground": color.info.emphasis,
    "extensionBadge.remoteForeground": color.foreground.onEmphasis,
    "extensionIcon.starForeground": color.attention.foreground,
    "extensionIcon.verifiedForeground": color.info.foreground,
    "extensionIcon.preReleaseForeground": color.accent.secondary,
    "extensionIcon.sponsorForeground": color.accent.foreground,
    "extensionIcon.privateForeground": color.foreground.muted,
    "mcpIcon.starForeground": color.attention.foreground,
    "inputOption.activeBackground": alpha(color.accent.tertiary, 50),
    "inputOption.activeBorder": color.accent.tertiary,
    "inputOption.activeForeground": color.foreground.emphasis,
    "inputValidation.errorBackground": color.danger.emphasis,
    "inputValidation.errorBorder": color.danger.emphasis,
    "inputValidation.errorForeground": color.foreground.onEmphasis,
    "inputValidation.infoBackground": color.info.emphasis,
    "inputValidation.infoBorder": color.info.emphasis,
    "inputValidation.infoForeground": color.foreground.onEmphasis,
    "inputValidation.warningBackground": color.attention.emphasis,
    "inputValidation.warningBorder": color.attention.emphasis,
    "inputValidation.warningForeground": color.foreground.onEmphasis,

    // Modern UI
    "editor.border": color.border.default,
    "surface.border": color.border.muted,
    "modernActivityBarItem.activeBackground": alpha(
      color.accent.foreground,
      20,
    ),
    "modernActivityBarItem.hoverBackground": alpha(color.accent.foreground, 15),
    "modernActivityBarItem.activeForeground": color.foreground.onEmphasis,
    "modernActivityBarItem.hoverForeground": color.foreground.onEmphasis,
    "modernActivityBar.border": color.border.muted,

    // Window chrome and primary navigation
    "titleBar.activeForeground": color.foreground.muted,
    "titleBar.activeBackground": color.canvas.default,
    "titleBar.inactiveForeground": color.foreground.subtle,
    "titleBar.inactiveBackground": color.canvas.inset,
    "titleBar.border": color.border.muted,
    "activityBar.foreground": color.foreground.subtle,
    "activityBar.inactiveForeground": color.foreground.subtle,
    "activityBar.background": color.canvas.inset,
    "activityBar.activeBorder": color.accent.foreground,
    "activityBar.activeFocusBorder": color.accent.foreground,
    "activityBar.border": color.border.muted,
    "activityBarTop.foreground": color.foreground.subtle,
    "activityBarTop.inactiveForeground": color.foreground.subtle,
    "activityBarTop.background": color.canvas.inset,
    "activityBarTop.activeBorder": color.accent.foreground,
    "activityBarTop.activeFocusBorder": color.accent.foreground,
    "activityBarTop.border": color.border.muted,
    "activityBarBadge.foreground": color.accent.foreground,
    "activityBarBadge.background": color.canvas.inset,
    "sideBar.foreground": color.foreground.muted,
    "sideBar.background": color.canvas.inset,
    "sideBar.border": color.border.muted,
    "sideBarTitle.foreground": color.foreground.muted,
    "sideBarSectionHeader.foreground": color.foreground.muted,
    "sideBarSectionHeader.background": color.canvas.inset,
    "sideBarSectionHeader.border": color.border.muted,
    "sideBar.dropBackground": alpha(color.canvas.inset, 80),
    "commandCenter.activeForeground": color.foreground.muted,
    "commandCenter.activeBackground": color.canvas.default,
    "commandCenter.inactiveForeground": color.foreground.muted,
    "commandCenter.inactiveBorder": color.border.muted,
    "commandCenter.foreground": color.foreground.muted,
    "commandCenter.background": color.canvas.inset,
    "commandCenter.border": color.border.muted,
    "commandCenter.activeBorder": color.accent.foreground,

    // Lists, trees, notifications, and pickers
    "list.hoverForeground": color.foreground.emphasis,
    "list.inactiveSelectionForeground": color.foreground.emphasis,
    "list.activeSelectionForeground": color.foreground.emphasis,
    "list.activeSelectionIconForeground": color.foreground.emphasis,
    "list.hoverBackground": color.interaction.hover,
    "list.inactiveSelectionBackground": color.interaction.selectedInactive,
    "list.activeSelectionBackground": color.interaction.selected,
    "list.focusForeground": color.foreground.emphasis,
    "list.focusBackground": color.interaction.selected,
    "list.focusOutline": color.accent.foreground,
    "list.inactiveFocusBackground": color.interaction.selectedInactive,
    "list.highlightForeground": color.foreground.default,
    "tree.indentGuidesStroke": color.border.default,
    "notificationCenterHeader.foreground": color.foreground.default,
    "notificationCenterHeader.background": color.canvas.inset,
    "notifications.foreground": color.foreground.default,
    "notifications.background": color.canvas.overlay,
    "notifications.border": color.border.muted,
    "notificationsErrorIcon.foreground": color.danger.foreground,
    "notificationsWarningIcon.foreground": color.attention.foreground,
    "notificationsInfoIcon.foreground": color.info.foreground,
    "activityWarningBadge.foreground": color.foreground.onEmphasis,
    "activityWarningBadge.background": color.attention.emphasis,
    "activityErrorBadge.foreground": color.foreground.onEmphasis,
    "activityErrorBadge.background": color.danger.emphasis,
    "pickerGroup.border": color.border.emphasis,
    "pickerGroup.foreground": color.foreground.subtle,
    "quickInput.background": color.canvas.overlay,
    "quickInput.foreground": color.foreground.default,
    "quickInput.border": color.border.default,
    "list.dropBackground": color.interaction.selected,
    "list.errorForeground": color.danger.foreground,
    "list.invalidItemForeground": color.danger.foreground,
    "list.warningForeground": color.attention.foreground,
    "list.filterMatchBackground": color.canvas.overlay,
    "list.filterMatchBorder": color.border.default,
    "listFilterWidget.background": color.canvas.overlay,
    "listFilterWidget.noMatchesOutline": color.danger.foreground,
    "listFilterWidget.outline": color.border.muted,
    "menu.background": color.canvas.overlay,
    "menu.border": color.border.default,
    "menu.foreground": color.foreground.emphasis,
    "menu.selectionBackground": color.interaction.selected,
    "menu.selectionBorder": color.border.muted,
    "menu.selectionForeground": color.foreground.emphasis,
    "menu.separatorBackground": color.foreground.default,
    "menubar.selectionBackground": color.interaction.selected,
    "menubar.selectionBorder": color.border.muted,
    "menubar.selectionForeground": color.foreground.emphasis,
    "notificationCenter.border": color.border.muted,
    "notificationLink.foreground": color.foreground.default,
    "notificationToast.border": color.border.muted,
    "selection.background": color.interaction.selected,
    "quickInputList.focusBackground": color.interaction.selected,
    "quickInputList.focusForeground": color.foreground.emphasis,
    "quickInputList.focusIconForeground": color.foreground.emphasis,
    "quickInputList.focusHighlightForeground": color.accent.subtle,
    "quickInputList.hoverBackground": color.interaction.hover,
    "quickInputTitle.background": color.canvas.overlay,
    "toolbar.hoverBackground": color.interaction.hover,
    "toolbar.hoverOutline": color.border.default,
    "toolbar.activeBackground": color.interaction.pressed,
    "actionBar.toggledBackground": color.interaction.selected,

    // Status bar
    "statusBar.foreground": color.foreground.muted,
    "statusBar.background": color.canvas.default,
    "statusBar.border": color.border.default,
    "statusBar.focusBorder": alpha(color.accent.foreground, 50),
    "statusBar.noFolderBackground": color.canvas.default,
    "statusBar.debuggingForeground": color.foreground.onEmphasis,
    "statusBar.debuggingBackground": color.control.primary.background,
    "statusBarItem.prominentBackground": color.canvas.overlay,
    "statusBarItem.prominentForeground": color.foreground.onEmphasis,
    "statusBarItem.remoteForeground": color.foreground.default,
    "statusBarItem.remoteBackground": color.canvas.overlay,
    "statusBarItem.hoverBackground": color.canvas.overlay,
    "statusBarItem.hoverForeground": color.foreground.emphasis,
    "statusBarItem.activeBackground": color.canvas.overlay,
    "statusBarItem.focusBorder": color.accent.foreground,
    "statusBar.debuggingBorder": color.border.default,
    "statusBar.noFolderBorder": color.border.default,
    "statusBar.noFolderForeground": color.foreground.muted,
    "statusBarItem.prominentHoverBackground": color.canvas.overlay,

    // Editor groups, tabs, and breadcrumbs
    "editorGroupHeader.tabsBackground": color.canvas.default,
    "editorGroupHeader.tabsBorder": color.border.default,
    "editorGroup.border": color.border.default,
    "tab.activeForeground": color.foreground.emphasis,
    "tab.inactiveForeground": color.foreground.muted,
    "tab.selectedForeground": color.foreground.emphasis,
    "tab.inactiveBackground": color.canvas.default,
    "tab.activeBackground": color.canvas.default,
    "tab.selectedBackground": color.canvas.overlay,
    "tab.hoverBackground": color.canvas.default,
    "tab.hoverForeground": color.foreground.emphasis,
    "tab.border": color.border.default,
    "tab.activeBorder": color.border.default,
    "tab.activeBorderTop": color.border.default,
    "tab.selectedBorderTop": color.accent.foreground,
    "tab.lastPinnedBorder": color.border.default,
    "tab.activeModifiedBorder": color.border.default,
    "tab.inactiveModifiedBorder": color.border.default,
    "tab.unfocusedActiveBackground": color.canvas.default,
    "tab.unfocusedActiveForeground": color.foreground.emphasis,
    "tab.unfocusedActiveModifiedBorder": color.border.default,
    "tab.unfocusedHoverBackground": color.canvas.default,
    "tab.unfocusedHoverBorder": color.border.default,
    "tab.unfocusedInactiveBackground": color.canvas.default,
    "tab.unfocusedInactiveForeground": color.foreground.muted,
    "tab.unfocusedInactiveModifiedBorder": color.border.default,
    "tab.unfocusedActiveBorder": color.border.default,
    "tab.unfocusedActiveBorderTop": color.border.default,
    "breadcrumb.foreground": color.foreground.default,
    "breadcrumb.focusForeground": color.foreground.default,
    "breadcrumb.activeSelectionForeground": color.foreground.emphasis,
    "breadcrumbPicker.background": color.canvas.default,
    "breadcrumb.background": color.canvas.default,
    "editorGroup.dropBackground": alpha(color.canvas.inset, 80),
    "editorGroup.emptyBackground": color.canvas.default,
    "editorGroup.focusedEmptyBorder": color.border.default,
    "editorGroupHeader.noTabsBackground": color.canvas.default,

    // Editor canvas, selection, and guides
    "editor.foreground": color.foreground.prominent,
    "editor.background": color.canvas.default,
    "editor.foldBackground": alpha(color.canvas.overlay, 10),
    "editor.lineHighlightBackground": alpha(
      color.canvas.raised,
      OVERLAY_RESTING_ALPHA,
    ),
    "editorLineNumber.foreground": color.foreground.subtle,
    "editorLineNumber.activeForeground": color.foreground.default,
    "editorWhitespace.foreground": color.foreground.subtle,
    "editorCursor.foreground": color.foreground.emphasis,
    "editor.findMatchBackground": color.canvas.overlay,
    "editor.findMatchHighlightBackground": alpha(
      color.canvas.overlay,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editor.linkedEditingBackground": alpha(color.accent.secondaryEmphasis, 25),
    "editor.inactiveSelectionBackground": alpha(color.accent.secondary, 12.5),
    "editor.selectionBackground": alpha(color.accent.secondaryEmphasis, 25),
    "editor.selectionHighlightBackground": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "editor.wordHighlightBackground": alpha(
      color.canvas.raised,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editor.wordHighlightBorder": alpha(color.canvas.raised, 60),
    "editor.wordHighlightStrongBackground": alpha(
      color.canvas.raised,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editor.wordHighlightStrongBorder": alpha(color.canvas.raised, 60),
    "editorBracketMatch.background": alpha(color.canvas.overlay, 90),
    "editorBracketMatch.border": alpha(color.border.emphasis, 90),
    "editor.selectionForeground": color.foreground.emphasis,
    "editorInlayHint.background": alpha(
      color.canvas.overlay,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editorInlayHint.foreground": color.foreground.muted,
    "editorInlayHint.typeBackground": alpha(
      color.canvas.overlay,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editorInlayHint.typeForeground": color.foreground.muted,
    "editor.findMatchBorder": alpha(
      color.accent.secondaryEmphasis,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editor.findRangeHighlightBackground": alpha(color.accent.secondary, 20),
    "editor.hoverHighlightBackground": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "editor.rangeHighlightBackground": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "editor.symbolHighlightBackground": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "editor.snippetFinalTabstopHighlightBackground": alpha(
      color.accent.secondary,
      25,
    ),
    "editor.snippetFinalTabstopHighlightBorder": alpha(
      color.accent.secondary,
      25,
    ),
    "editor.snippetTabstopHighlightBackground": alpha(
      color.accent.secondary,
      25,
    ),
    "editor.snippetTabstopHighlightBorder": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "editor.wordHighlightTextBackground": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "editorCursor.background": color.attention.foreground,
    "editorIndentGuide.activeBackground": color.foreground.default,
    "editorIndentGuide.activeBackground1": color.foreground.default,
    "editorIndentGuide.background": color.border.muted,
    "editorIndentGuide.background1": color.border.muted,
    "editorInlayHint.parameterForeground": color.foreground.muted,
    "editorInlayHint.parameterBackground": alpha(
      color.canvas.overlay,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editorStickyScroll.background": color.canvas.default,
    "editorStickyScrollHover.background": alpha(
      color.canvas.raised,
      OVERLAY_RESTING_ALPHA,
    ),
    "editorStickyScroll.border": color.border.muted,
    "editorStickyScroll.shadow": alpha(color.canvas.inset, 25),
    "editorGhostText.foreground": color.foreground.emphasis,
    "editorBracketHighlight.foreground1": color.brackets.one,
    "editorBracketHighlight.foreground2": color.brackets.two,
    "editorBracketHighlight.foreground3": color.brackets.three,
    "editorBracketHighlight.foreground4": color.brackets.four,
    "editorBracketHighlight.foreground5": color.brackets.five,
    "editorBracketHighlight.foreground6": color.brackets.six,
    "editorBracketHighlight.unexpectedBracket.foreground":
      color.danger.foreground,

    // Editor diagnostics, rulers, and widgets
    "editorWidget.background": color.canvas.overlay,
    "editorCodeLens.foreground": color.foreground.default,
    "editorError.foreground": color.danger.foreground,
    "editorHint.foreground": color.accent.secondaryEmphasis,
    "editorHoverWidget.background": color.canvas.overlay,
    "editorHoverWidget.foreground": color.foreground.emphasis,
    "editorHoverWidget.border": color.border.emphasis,
    "editorInfo.foreground": color.info.foreground,
    "editorLink.activeForeground": color.foreground.default,
    "editorMarkerNavigation.background": color.canvas.default,
    "editorMarkerNavigationError.background": alpha(color.danger.muted, 20),
    "editorMarkerNavigationInfo.background": alpha(color.info.muted, 20),
    "editorMarkerNavigationWarning.background": alpha(
      color.attention.muted,
      20,
    ),
    "editorPane.background": color.canvas.default,
    "editorRuler.foreground": color.canvas.inset,
    "editorSuggestWidget.background": color.canvas.overlay,
    "editorSuggestWidget.border": color.border.muted,
    "editorSuggestWidget.foreground": color.foreground.emphasis,
    "editorSuggestWidget.highlightForeground": color.foreground.default,
    "editorSuggestWidget.selectedBackground": color.canvas.overlay,
    "editorUnnecessaryCode.opacity": alpha(color.foreground.emphasis, 80),
    "editorWarning.foreground": color.attention.foreground,
    "editorWidget.foreground": color.foreground.emphasis,
    "editorWidget.border": color.border.default,
    "editorWidget.resizeBorder": color.border.default,
    "searchEditor.findMatchBackground": color.canvas.overlay,
    "searchEditor.findMatchBorder": color.border.default,
    "notebook.symbolHighlightBackground": alpha(color.canvas.overlay, 15),
    "editorCommentsWidget.rangeBackground": alpha(color.accent.tertiary, 15),
    "editorCommentsWidget.rangeActiveBackground": alpha(
      color.accent.tertiary,
      25,
    ),

    // Source control, diffs, and scrolling
    "editorGutter.modifiedBackground": alpha(color.sourceControl.modified, 60),
    "editorGutter.addedBackground": alpha(color.sourceControl.added, 60),
    "editorGutter.deletedBackground": alpha(color.sourceControl.deleted, 60),
    "diffEditor.insertedLineBackground": alpha(color.sourceControl.added, 15),
    "diffEditor.insertedTextBackground": alpha(color.sourceControl.added, 10),
    "diffEditor.removedLineBackground": alpha(color.sourceControl.deleted, 15),
    "diffEditor.removedTextBackground": alpha(color.sourceControl.deleted, 10),
    "scrollbar.shadow": color.canvas.default,
    "scrollbarSlider.background": alpha(
      color.canvas.raised,
      OVERLAY_RESTING_ALPHA,
    ),
    "scrollbarSlider.hoverBackground": alpha(
      color.canvas.raised,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "scrollbarSlider.activeBackground": alpha(
      color.canvas.raised,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "editorOverviewRuler.border": alpha(color.border.muted, 25),
    "minimapSlider.background": alpha(
      color.canvas.raised,
      OVERLAY_RESTING_ALPHA,
    ),
    "minimapSlider.hoverBackground": alpha(
      color.canvas.raised,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "minimapSlider.activeBackground": alpha(
      color.canvas.raised,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "diffEditor.border": color.canvas.default,
    "editorGutter.background": color.canvas.default,
    "editorGutter.commentRangeForeground": color.foreground.muted,
    "editorOverviewRuler.addedForeground": color.sourceControl.added,
    "editorOverviewRuler.bracketMatchForeground":
      color.accent.secondaryEmphasis,
    "editorOverviewRuler.commonContentForeground": color.foreground.default,
    "editorOverviewRuler.currentContentForeground": color.accent.tertiary,
    "editorOverviewRuler.deletedForeground": color.sourceControl.deleted,
    "editorOverviewRuler.errorForeground": color.danger.foreground,
    "editorOverviewRuler.findMatchForeground": alpha(
      color.foreground.default,
      60,
    ),
    "editorOverviewRuler.incomingContentForeground": color.success.foreground,
    "editorOverviewRuler.infoForeground": color.info.foreground,
    "editorOverviewRuler.modifiedForeground": color.sourceControl.modified,
    "editorOverviewRuler.rangeHighlightForeground": alpha(
      color.accent.secondary,
      25,
    ),
    "editorOverviewRuler.selectionHighlightForeground": alpha(
      color.accent.secondary,
      25,
    ),
    "editorOverviewRuler.warningForeground": color.attention.foreground,
    "editorOverviewRuler.wordHighlightForeground": alpha(
      color.accent.foreground,
      60,
    ),
    "editorOverviewRuler.wordHighlightStrongForeground": alpha(
      color.accent.foreground,
      60,
    ),
    "editorOverviewRuler.wordHighlightTextForeground": alpha(
      color.accent.secondary,
      25,
    ),
    "editorOverviewRuler.inlineChatInserted": color.sourceControl.added,
    "editorOverviewRuler.inlineChatRemoved": color.sourceControl.deleted,
    "merge.border": color.border.default,
    "merge.commonContentBackground": alpha(color.canvas.inset, 10),
    "merge.commonHeaderBackground": alpha(color.canvas.inset, 20),
    "merge.currentContentBackground": alpha(color.accent.secondary, 20),
    "merge.currentHeaderBackground": alpha(color.accent.tertiary, 20),
    "merge.incomingContentBackground": alpha(color.success.muted, 10),
    "merge.incomingHeaderBackground": alpha(color.success.muted, 20),
    "minimap.findMatchHighlight": alpha(color.foreground.default, 60),
    "minimap.selectionHighlight": alpha(color.accent.secondaryEmphasis, 25),
    "minimap.selectionOccurrenceHighlight": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "minimap.errorHighlight": color.danger.foreground,
    "minimap.warningHighlight": color.attention.foreground,
    "minimap.infoHighlight": color.info.foreground,
    "minimap.chatEditHighlight": color.accent.tertiary,
    "minimapGutter.addedBackground": color.sourceControl.added,
    "minimapGutter.modifiedBackground": color.sourceControl.modified,
    "minimapGutter.deletedBackground": color.sourceControl.deleted,
    "editorMinimap.inlineChatInserted": color.sourceControl.added,

    // Panels and debugging
    "panel.background": color.canvas.inset,
    "panel.border": color.border.muted,
    "panelTitle.activeBorder": color.border.default,
    "panelTitle.activeForeground": color.foreground.emphasis,
    "panelTitle.inactiveForeground": color.foreground.default,
    "panelInput.border": color.border.muted,
    "debugIcon.breakpointForeground": color.danger.foreground,
    "debugConsole.infoForeground": color.info.foreground,
    "debugConsole.warningForeground": color.attention.foreground,
    "debugConsole.errorForeground": color.danger.foreground,
    "debugConsole.sourceForeground": color.foreground.subtle,
    "debugConsoleInputIcon.foreground": color.accent.secondaryEmphasis,
    "debugTokenExpression.name": color.accent.tertiary,
    "debugTokenExpression.value": color.accent.subtle,
    "debugTokenExpression.string": color.accent.subtle,
    "debugTokenExpression.boolean": color.success.foreground,
    "debugTokenExpression.number": color.success.foreground,
    "debugTokenExpression.error": color.danger.foreground,
    "debugExceptionWidget.background": color.canvas.default,
    "debugExceptionWidget.border": color.border.muted,
    "testing.iconFailed": color.danger.foreground,
    "testing.iconErrored": color.danger.foreground,
    "testing.iconPassed": color.success.foreground,
    "testing.iconQueued": color.foreground.default,
    "testing.iconUnset": color.foreground.muted,
    "testing.iconSkipped": color.attention.foreground,
    "testing.runAction": color.success.emphasis,
    "testing.peekBorder": color.border.muted,
    "testing.peekHeaderBackground": color.canvas.default,
    "testing.message.info.decorationForeground": color.info.foreground,
    "ports.iconRunningProcessForeground": color.success.foreground,

    // Gauges and charts
    "gauge.foreground": color.info.foreground,
    "gauge.background": alpha(color.info.muted, 30),
    "gauge.border": color.border.default,
    "gauge.warningForeground": color.attention.foreground,
    "gauge.warningBackground": alpha(color.attention.muted, 30),
    "gauge.errorForeground": color.danger.foreground,
    "gauge.errorBackground": alpha(color.danger.muted, 30),
    "charts.foreground": color.foreground.default,
    "charts.lines": alpha(color.foreground.default, 50),
    "charts.blue": color.accent.tertiary,
    "charts.red": color.danger.foreground,
    "charts.yellow": color.attention.foreground,
    "charts.orange": color.attention.muted,
    "charts.green": color.success.foreground,
    "charts.purple": color.accent.secondaryEmphasis,

    // Outline and symbol icons
    "symbolIcon.arrayForeground": color.attention.muted,
    "symbolIcon.booleanForeground": color.accent.tertiary,
    "symbolIcon.classForeground": color.attention.muted,
    "symbolIcon.colorForeground": color.accent.subtle,
    "symbolIcon.constructorForeground": color.accent.secondaryEmphasis,
    "symbolIcon.enumeratorForeground": color.attention.muted,
    "symbolIcon.enumeratorMemberForeground": color.accent.tertiary,
    "symbolIcon.eventForeground": color.foreground.subtle,
    "symbolIcon.fieldForeground": color.attention.muted,
    "symbolIcon.fileForeground": color.attention.muted,
    "symbolIcon.folderForeground": color.attention.muted,
    "symbolIcon.functionForeground": color.accent.secondaryEmphasis,
    "symbolIcon.interfaceForeground": color.attention.muted,
    "symbolIcon.keyForeground": color.accent.tertiary,
    "symbolIcon.keywordForeground": color.syntax.keyword,
    "symbolIcon.methodForeground": color.accent.secondaryEmphasis,
    "symbolIcon.moduleForeground": color.syntax.type,
    "symbolIcon.namespaceForeground": color.syntax.type,
    "symbolIcon.nullForeground": color.accent.tertiary,
    "symbolIcon.numberForeground": color.success.foreground,
    "symbolIcon.objectForeground": color.attention.muted,
    "symbolIcon.operatorForeground": color.accent.subtle,
    "symbolIcon.packageForeground": color.attention.muted,
    "symbolIcon.propertyForeground": color.attention.muted,
    "symbolIcon.referenceForeground": color.accent.tertiary,
    "symbolIcon.snippetForeground": color.accent.tertiary,
    "symbolIcon.stringForeground": color.accent.subtle,
    "symbolIcon.structForeground": color.attention.muted,
    "symbolIcon.textForeground": color.accent.subtle,
    "symbolIcon.typeParameterForeground": color.accent.subtle,
    "symbolIcon.unitForeground": color.accent.tertiary,
    "symbolIcon.variableForeground": color.attention.muted,
    "symbolIcon.constantForeground": color.success.foreground,

    // Integrated terminal
    "terminal.foreground": color.foreground.emphasis,
    "terminal.ansiBlack": color.ansi.black,
    "terminal.ansiRed": color.ansi.red,
    "terminal.ansiGreen": color.ansi.green,
    "terminal.ansiYellow": color.ansi.yellow,
    "terminal.ansiBlue": color.ansi.blue,
    "terminal.ansiMagenta": color.ansi.magenta,
    "terminal.ansiCyan": color.ansi.cyan,
    "terminal.ansiWhite": color.ansi.white,
    "terminal.ansiBrightBlack": color.ansi.brightBlack,
    "terminal.ansiBrightRed": color.ansi.brightRed,
    "terminal.ansiBrightGreen": color.ansi.brightGreen,
    "terminal.ansiBrightYellow": color.ansi.brightYellow,
    "terminal.ansiBrightBlue": color.ansi.brightBlue,
    "terminal.ansiBrightMagenta": color.ansi.brightMagenta,
    "terminal.ansiBrightCyan": color.ansi.brightCyan,
    "terminal.ansiBrightWhite": color.ansi.brightWhite,
    "terminal.background": color.canvas.inset,
    "terminal.border": color.border.muted,
    "terminal.findMatchBackground": alpha(
      color.canvas.overlay,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "terminal.findMatchBorder": color.border.default,
    "terminal.findMatchHighlightBackground": alpha(
      color.canvas.overlay,
      OVERLAY_ENGAGED_ALPHA,
    ),
    "terminal.selectionBackground": alpha(color.accent.secondary, 50),
    "terminal.inactiveSelectionBackground": alpha(color.accent.secondary, 12.5),
    "terminal.tab.activeBorder": color.accent.foreground,
    "terminalCursor.background": color.canvas.inset,
    "terminalCursor.foreground": color.foreground.emphasis,

    // Bracket pairs
    "editorBracketPairGuide.activeBackground1": alpha(
      color.brackets.one,
      BRACKET_GUIDE_ACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.activeBackground2": alpha(
      color.brackets.two,
      BRACKET_GUIDE_ACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.activeBackground3": alpha(
      color.brackets.three,
      BRACKET_GUIDE_ACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.activeBackground4": alpha(
      color.brackets.four,
      BRACKET_GUIDE_ACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.activeBackground5": alpha(
      color.brackets.five,
      BRACKET_GUIDE_ACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.activeBackground6": alpha(
      color.brackets.six,
      BRACKET_GUIDE_ACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.background1": alpha(
      color.brackets.one,
      BRACKET_GUIDE_INACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.background2": alpha(
      color.brackets.two,
      BRACKET_GUIDE_INACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.background3": alpha(
      color.brackets.three,
      BRACKET_GUIDE_INACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.background4": alpha(
      color.brackets.four,
      BRACKET_GUIDE_INACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.background5": alpha(
      color.brackets.five,
      BRACKET_GUIDE_INACTIVE_ALPHA,
    ),
    "editorBracketPairGuide.background6": alpha(
      color.brackets.six,
      BRACKET_GUIDE_INACTIVE_ALPHA,
    ),

    // Source control decorations
    "gitDecoration.addedResourceForeground": color.sourceControl.added,
    "gitDecoration.modifiedResourceForeground": color.sourceControl.modified,
    "gitDecoration.renamedResourceForeground": color.sourceControl.renamed,
    "gitDecoration.deletedResourceForeground": color.sourceControl.deleted,
    "gitDecoration.untrackedResourceForeground": color.sourceControl.untracked,
    "gitDecoration.ignoredResourceForeground": alpha(
      color.sourceControl.ignored,
      50,
    ),
    "gitDecoration.conflictingResourceForeground":
      color.sourceControl.conflicting,
    "gitDecoration.stageModifiedResourceForeground":
      color.sourceControl.stageModified,
    "gitDecoration.stageDeletedResourceForeground":
      color.sourceControl.stageDeleted,
    "gitDecoration.submoduleResourceForeground": color.sourceControl.submodule,

    // Debugging and peek views
    "debugToolBar.background": color.canvas.default,
    "editor.stackFrameHighlightBackground": color.canvas.default,
    "editor.focusedStackFrameHighlightBackground": color.canvas.inset,
    "peekViewEditor.matchHighlightBackground": alpha(
      color.accent.secondary,
      25,
    ),
    "peekViewResult.matchHighlightBackground": alpha(
      color.accent.secondary,
      25,
    ),
    "peekViewEditor.background": color.canvas.inset,
    "peekViewResult.background": color.canvas.inset,
    "debugToolBar.border": color.border.muted,
    "peekView.border": color.accent.foreground,
    "peekViewEditor.matchHighlightBorder": alpha(color.accent.secondary, 3),
    "peekViewEditorGutter.background": color.canvas.inset,
    "peekViewResult.fileForeground": color.foreground.muted,
    "peekViewResult.lineForeground": color.foreground.muted,
    "peekViewResult.selectionBackground": alpha(
      color.accent.secondaryEmphasis,
      25,
    ),
    "peekViewResult.selectionForeground": color.foreground.emphasis,
    "peekViewTitle.background": color.canvas.inset,
    "peekViewTitleDescription.foreground": color.foreground.muted,
    "peekViewTitleLabel.foreground": color.foreground.emphasis,

    // Settings and welcome page
    "settings.headerForeground": color.foreground.emphasis,
    "settings.modifiedItemIndicator": color.foreground.default,
    "welcomePage.progress.foreground": color.accent.foreground,
    "welcomePage.tileBackground": color.canvas.overlay,
    "welcomePage.tileHoverBackground": color.canvas.overlay,
    "settings.checkboxBackground": color.canvas.overlay,
    "settings.checkboxBorder": color.border.muted,
    "settings.checkboxForeground": color.foreground.default,
    "settings.dropdownBackground": color.canvas.inset,
    "settings.dropdownBorder": color.border.muted,
    "settings.dropdownForeground": color.foreground.default,
    "settings.dropdownListBorder": color.border.muted,
    "settings.numberInputBackground": color.canvas.inset,
    "settings.numberInputBorder": color.border.muted,
    "settings.numberInputForeground": color.foreground.default,
    "settings.textInputBackground": color.canvas.inset,
    "settings.textInputBorder": color.border.muted,
    "settings.textInputForeground": color.foreground.default,
    "walkThrough.embeddedEditorBackground": color.canvas.default,
    "welcomePage.background": color.canvas.default,
    "widget.border": color.border.default,
    "widget.shadow": alpha(color.canvas.inset, 50),

    // Chat, agents, and inline editing
    "chat.requestBackground": alpha(color.canvas.default, 0),
    "chat.requestBorder": color.border.default,
    "chat.requestBubbleBackground": alpha(color.canvas.overlay, 60),
    "chat.requestBubbleHoverBackground": alpha(color.canvas.overlay, 50),
    "chat.requestCodeBorder": alpha(color.border.emphasis, 60),
    "chat.slashCommandBackground": color.canvas.overlay,
    "chat.slashCommandForeground": color.foreground.emphasis,
    "chat.avatarBackground": color.canvas.overlay,
    "chat.avatarForeground": color.foreground.emphasis,
    "chat.editedFileForeground": color.sourceControl.modified,
    "chat.linesAddedForeground": alpha(color.sourceControl.added, 60),
    "chat.linesRemovedForeground": alpha(color.sourceControl.deleted, 60),
    "chat.checkpointSeparator": color.canvas.overlay,
    "chat.thinkingShimmer": alpha(color.accent.subtle, 84),
    "chat.inputWorkingBorderColor1": color.accent.foreground,
    "chat.inputWorkingBorderColor2": color.accent.secondaryEmphasis,
    "chat.inputWorkingBorderColor3": color.accent.tertiary,
    "chatManagement.sashBorder": color.border.muted,
    "agents.background": color.canvas.default,
    "agentsPanel.background": color.canvas.default,
    "agentsPanel.foreground": color.foreground.default,
    "agentsPanel.border": color.border.muted,
    "agentsGradient.tintColor": color.accent.foreground,
    "agentsChatInput.background": color.canvas.overlay,
    "agentsChatInput.foreground": color.foreground.default,
    "agentsChatInput.border": color.border.default,
    "agentsChatInput.focusBorder": color.accent.foreground,
    "agentsChatInput.placeholderForeground": color.foreground.subtle,
    "agentsNewSessionButton.background": alpha(color.canvas.default, 0),
    "agentsNewSessionButton.foreground": color.foreground.default,
    "agentsNewSessionButton.border": color.border.default,
    "agentsNewSessionButton.hoverBackground": color.interaction.hover,
    "agentsBadge.background": color.accent.foreground,
    "agentsBadge.foreground": color.foreground.onEmphasis,
    "agentsUnreadBadge.background": color.accent.foreground,
    "agentsUnreadBadge.foreground": color.foreground.onEmphasis,
    "agentSessionReadIndicator.foreground": color.accent.foreground,
    "agentSessionSelectedBadge.border": color.accent.foreground,
    "agentSessionSelectedUnfocusedBadge.border": alpha(
      color.accent.foreground,
      50,
    ),
    "agentStatusIndicator.background": color.accent.foreground,
    "aiCustomizationManagement.sashBorder": color.border.muted,
    "inlineChat.background": color.canvas.default,
    "inlineChat.foreground": color.foreground.default,
    "inlineChat.border": color.border.muted,
    "inlineChat.shadow": alpha(color.canvas.inset, 50),
    "inlineChatInput.background": color.canvas.default,
    "inlineChatInput.border": color.border.default,
    "inlineChatInput.focusBorder": color.accent.tertiary,
    "inlineChatInput.placeholderForeground": color.foreground.muted,
    "inlineChatDiff.inserted": alpha(color.sourceControl.added, 20),
    "inlineChatDiff.removed": alpha(color.sourceControl.deleted, 20),
    "interactive.activeCodeBorder": color.accent.tertiary,
    "interactive.inactiveCodeBorder": color.border.default,
  };
}

module.exports = createWorkbenchColors;
