const chroma = require("chroma-js");

const TRANSPARENT = "#00000000";

function alpha(value, opacity) {
  if (!Number.isFinite(opacity) || opacity < 0 || opacity > 1) {
    throw new RangeError("Alpha opacity must be between 0 and 1");
  }

  return chroma(value).alpha(opacity).hex();
}

function createWorkbenchColors(color) {
  return {
    // Base text and links
    focusBorder: color.accent.secondary.background,
    foreground: color.foreground.default,
    disabledForeground: alpha(color.foreground.subtle, 0.75),
    descriptionForeground: color.foreground.subtle,
    errorForeground: color.danger.foreground,
    "textLink.foreground": color.accent.primary.background,
    "textLink.activeForeground": color.accent.primary.background,
    "textBlockQuote.background": color.canvas.inset,
    "textBlockQuote.border": alpha(color.accent.tertiary.background, 0.5),
    "textCodeBlock.background": color.canvas.default,
    "textPreformat.foreground": color.accent.tertiary.background,
    "textPreformat.background": alpha(color.accent.tertiary.background, 0.125),
    "textPreformat.border": color.border.muted,
    "textSeparator.foreground": color.foreground.default,
    "icon.foreground": color.foreground.muted,
    "keybindingLabel.background": alpha(color.canvas.raised, 0.5),
    "keybindingLabel.foreground": color.accent.secondary.background,
    "keybindingLabel.border": color.border.emphasis,
    "keybindingLabel.bottomBorder": color.accent.secondary.background,
    "keybindingTable.headerBackground": color.canvas.inset,
    "keybindingTable.rowsBackground": color.canvas.default,
    "banner.background": color.canvas.overlay,
    "banner.foreground": color.foreground.emphasis,
    "banner.iconForeground": color.accent.secondary.background,

    // Buttons, inputs, and controls
    "button.background": color.control.primary.background,
    "button.foreground": color.control.primary.foreground,
    "button.border": color.control.secondary.border,
    "button.separator": color.control.primary.border,
    "button.hoverBackground": color.control.primary.hoverBackground,
    "button.secondaryBackground": color.control.secondary.background,
    "button.secondaryForeground": color.control.secondary.foreground,
    "button.secondaryBorder": color.control.secondary.border,
    "button.secondaryHoverBackground": color.control.secondary.hoverBackground,
    "checkbox.background": color.canvas.overlay,
    "checkbox.border": color.border.emphasis,
    "checkbox.foreground": color.foreground.emphasis,
    "checkbox.selectBackground": color.canvas.overlay,
    "checkbox.selectBorder": color.border.emphasis,
    "checkbox.disabled.background": color.canvas.overlay,
    "checkbox.disabled.foreground": color.foreground.default,
    "dropdown.background": color.canvas.overlay,
    "dropdown.border": color.border.emphasis,
    "dropdown.foreground": color.foreground.emphasis,
    "dropdown.listBackground": color.canvas.overlay,
    "radio.activeForeground": color.foreground.emphasis,
    "radio.activeBackground": color.canvas.overlay,
    "radio.activeBorder": color.border.emphasis,
    "radio.inactiveForeground": color.foreground.muted,
    "radio.inactiveBackground": color.canvas.overlay,
    "radio.inactiveBorder": color.border.emphasis,
    "radio.inactiveHoverBackground": alpha(color.interaction.hover, 0.5),
    "sash.hoverBorder": color.control.primary.background,
    "input.background": color.canvas.default,
    "input.border": color.border.default,
    "input.foreground": color.foreground.emphasis,
    "input.placeholderForeground": color.foreground.subtle,
    "badge.foreground": color.badge.foreground,
    "badge.background": color.badge.background,
    "progressBar.background": color.accent.primary.background,
    "extensionButton.prominentBackground": color.control.primary.background,
    "extensionButton.prominentForeground": color.control.primary.foreground,
    "extensionButton.prominentHoverBackground":
      color.control.primary.hoverBackground,
    "extensionButton.background": color.control.primary.background,
    "extensionButton.foreground": color.control.primary.foreground,
    "extensionButton.hoverBackground": color.control.primary.hoverBackground,
    "extensionButton.separator": color.control.primary.border,
    "extensionButton.border": color.control.primary.border,
    "extensionBadge.remoteBackground": color.info.emphasis,
    "extensionBadge.remoteForeground": color.foreground.onEmphasis,
    "extensionIcon.starForeground": color.extensionIcon.star,
    "extensionIcon.verifiedForeground": color.extensionIcon.verified,
    "extensionIcon.preReleaseForeground": color.extensionIcon.preRelease,
    "extensionIcon.sponsorForeground": color.extensionIcon.sponsor,
    "extensionIcon.privateForeground": color.extensionIcon.private,
    "mcpIcon.starForeground": color.attention.foreground,
    "inputOption.activeBackground": alpha(
      color.accent.tertiary.background,
      0.5,
    ),
    "inputOption.activeBorder": color.accent.tertiary.background,
    "inputOption.activeForeground": color.foreground.emphasis,
    "inputOption.hoverBackground": alpha(
      color.accent.tertiary.background,
      0.25,
    ),
    "inputValidation.errorBackground": color.danger.emphasis,
    "inputValidation.errorBorder": color.danger.emphasis,
    "inputValidation.errorForeground": color.foreground.onEmphasis,
    "inputValidation.infoBackground": color.info.emphasis,
    "inputValidation.infoBorder": color.info.emphasis,
    "inputValidation.infoForeground": color.foreground.onEmphasis,
    "inputValidation.warningBackground": color.attention.emphasis,
    "inputValidation.warningBorder": color.attention.emphasis,
    "inputValidation.warningForeground": color.foreground.onEmphasis,

    // Modern UI
    // contrastBorder: color.border.emphasis,
    // contrastActiveBorder: color.accent.primary.background,
    "surface.background": color.canvas.overlay,
    "surface.foreground": color.foreground.default,
    "editor.border": color.border.default,
    "surface.border": color.border.muted,
    "modernPanel.border": TRANSPARENT,
    "modernSash.gripForeground": color.border.emphasis,
    "modernTab.activeBackground": alpha(color.interaction.selected, 0.5),
    "modernTab.activeForeground": color.foreground.emphasis,
    "modernTab.hoverBackground": alpha(color.interaction.hover, 0.5),
    "modernTab.hoverForeground": color.foreground.emphasis,
    "modernEditorTab.activeBackground": alpha(color.interaction.selected, 0.5),
    "modernEditorTab.activeActionBackground": alpha(
      color.interaction.selected,
      0.5,
    ),
    "modernEditorTab.activeForeground": color.foreground.emphasis,
    "modernEditorTab.inactiveBackground": color.canvas.default,
    "modernEditorTab.hoverBackground": alpha(color.interaction.hover, 0.5),
    "modernEditorTab.hoverActionBackground": alpha(
      color.interaction.hover,
      0.5,
    ),
    "modernEditorTab.hoverForeground": color.foreground.emphasis,
    "modernEditorTab.activeHoverBackground": alpha(
      color.interaction.hover,
      0.5,
    ),
    "modernEditorTab.activeHoverActionBackground": alpha(
      color.interaction.hover,
      0.5,
    ),
    "modernEditorTab.selectedActionBackground": alpha(
      color.interaction.selected,
      0.5,
    ),
    "modernActivityBar.background": color.canvas.inset,
    "modernActivityBar.inactiveBackground": color.canvas.inset,
    "modernActivityBarItem.activeForeground": color.foreground.emphasis,
    "modernActivityBarItem.activeBackground": alpha(
      color.interaction.selected,
      0.5,
    ),
    "modernActivityBarItem.hoverForeground": color.foreground.emphasis,
    "modernActivityBarItem.hoverBackground": alpha(
      color.interaction.hover,
      0.5,
    ),
    "modernActivityBar.border": color.border.muted,
    "modernUI.shellBackground": color.canvas.default,
    "modernUI.inactiveShellBackground": color.canvas.inset,

    // Workbench shell
    // Window chrome
    "titleBar.activeForeground": color.foreground.default,
    "titleBar.activeBackground": color.canvas.default,
    "titleBar.inactiveForeground": alpha(color.foreground.subtle, 0.5),
    "titleBar.inactiveBackground": color.canvas.inset,
    "titleBar.border": color.border.muted,
    "window.activeBorder": color.accent.secondary.background,
    "window.inactiveBorder": color.border.muted,

    // Activity bar and side bar
    "activityBar.foreground": color.foreground.muted,
    "activityBar.inactiveForeground": color.foreground.muted,
    "activityBar.background": color.canvas.inset,
    "activityBar.activeBackground": alpha(color.interaction.selected, 0.5),
    "activityBar.activeBorder": color.accent.secondary.background,
    "activityBar.activeFocusBorder": color.accent.secondary.background,
    "activityBar.border": color.border.muted,
    "activityBar.dropBorder": color.accent.secondary.background,
    "activityBarTop.foreground": color.foreground.emphasis,
    "activityBarTop.inactiveForeground": color.foreground.muted,
    "activityBarTop.background": color.canvas.inset,
    "activityBarTop.activeBackground": alpha(color.interaction.selected, 0.5),
    "activityBarTop.activeBorder": TRANSPARENT,
    "activityBarTop.activeFocusBorder": color.accent.secondary.background,
    "activityBarTop.border": color.border.muted,
    "activityBarTop.dropBorder": color.accent.secondary.background,
    "activityBarBadge.foreground": color.badge.foreground,
    "activityBarBadge.background": color.badge.background,
    "sideBar.foreground": color.foreground.muted,
    "sideBar.background": color.canvas.inset,
    "sideBar.border": color.border.muted,
    "sideBarTitle.foreground": color.foreground.muted,
    "sideBarTitle.border": TRANSPARENT,
    "sideBarSectionHeader.foreground": color.foreground.muted,
    "sideBarSectionHeader.background": color.canvas.inset,
    "sideBarSectionHeader.border": TRANSPARENT,
    "sideBar.dropBackground": alpha(color.canvas.inset, 0.8),
    "sideBarStickyScroll.background": color.canvas.inset,
    "sideBarStickyScroll.border": color.canvas.inset,
    "sideBarStickyScroll.shadow": alpha(color.canvas.inset, 0.5),
    "sideBarActivityBarTop.border": TRANSPARENT,

    // Profiles and command center
    "profileBadge.background": color.badge.background,
    "profileBadge.foreground": color.badge.foreground,
    "profiles.sashBorder": color.border.muted,
    "commandCenter.activeForeground": color.foreground.muted,
    "commandCenter.activeBackground": color.canvas.default,
    "commandCenter.inactiveForeground": color.foreground.muted,
    "commandCenter.inactiveBorder": color.border.muted,
    "commandCenter.foreground": color.foreground.muted,
    "commandCenter.background": color.canvas.inset,
    "commandCenter.border": color.border.muted,
    "commandCenter.activeBorder": color.accent.secondary.background,

    // Lists, trees, notifications, and pickers
    "list.hoverForeground": color.foreground.emphasis,
    "list.hoverBackground": alpha(color.interaction.hover, 0.5),
    "list.inactiveSelectionForeground": color.foreground.emphasis,
    "list.inactiveSelectionBackground": alpha(
      color.interaction.selectedInactive,
      0.5,
    ),
    "list.activeSelectionForeground": color.accent.secondary.foreground,
    "list.activeSelectionBackground": color.accent.secondary.background,
    "list.focusHighlightForeground": color.accent.secondary.foreground,
    "list.focusAndSelectionOutline": color.accent.secondary.background,
    "list.focusForeground": color.accent.secondary.foreground,
    "list.focusBackground": color.accent.secondary.background,
    "list.focusOutline": color.border.emphasis,
    "list.inactiveFocusBackground": alpha(
      color.interaction.selectedInactive,
      0.5,
    ),
    "list.inactiveFocusOutline": color.border.muted,
    "list.deemphasizedForeground": color.foreground.default,
    "list.dropBetweenBackground": color.accent.primary.background,
    "list.highlightForeground": color.foreground.emphasis,
    "tree.indentGuidesStroke": color.border.default,
    "notificationCenterHeader.foreground": color.foreground.default,
    "notificationCenterHeader.background": color.canvas.inset,
    "notifications.foreground": color.foreground.default,
    "notifications.background": color.canvas.overlay,
    "notifications.border": color.border.muted,
    "notificationsErrorIcon.foreground": color.danger.foreground,
    "notificationsWarningIcon.foreground": color.attention.foreground,
    "notificationsInfoIcon.foreground": color.info.foreground,
    "activityWarningBadge.foreground": color.foreground.onEmphasis,
    "activityWarningBadge.background": color.attention.emphasis,
    "activityErrorBadge.foreground": color.foreground.onEmphasis,
    "activityErrorBadge.background": color.danger.emphasis,
    "pickerGroup.border": color.border.emphasis,
    "pickerGroup.foreground": color.foreground.default,
    "quickInput.background": color.canvas.overlay,
    "quickInput.foreground": color.foreground.emphasis,
    "quickInput.border": color.border.default,
    "list.dropBackground": alpha(color.interaction.selected, 0.5),
    "list.errorForeground": color.danger.foreground,
    "list.invalidItemForeground": color.danger.foreground,
    "list.warningForeground": color.attention.foreground,
    "list.filterMatchBackground": alpha(color.interaction.highlighted, 0.5),
    "list.filterMatchBorder": color.border.default,
    "listFilterWidget.background": color.canvas.overlay,
    "listFilterWidget.noMatchesOutline": color.danger.foreground,
    "listFilterWidget.outline": color.border.muted,
    "menu.background": color.canvas.overlay,
    "menu.border": color.border.default,
    "menu.foreground": color.foreground.emphasis,
    "menu.selectionBackground": alpha(color.interaction.selected, 0.5),
    "menu.selectionBorder": color.border.muted,
    "menu.selectionForeground": color.foreground.emphasis,
    "menu.separatorBackground": color.foreground.default,
    "menubar.selectionBackground": alpha(color.interaction.selected, 0.5),
    "menubar.selectionBorder": color.border.muted,
    "menubar.selectionForeground": color.foreground.emphasis,
    "notificationCenter.border": color.border.muted,
    "notificationLink.foreground": color.foreground.default,
    "notificationToast.border": color.border.muted,
    "selection.background": alpha(color.interaction.selected, 0.5),
    "quickInputList.focusBackground": color.control.primary.background,
    "quickInputList.focusForeground": color.control.primary.foreground,
    "quickInputList.focusIconForeground": color.control.primary.foreground,
    "quickInputList.focusHighlightForeground": color.control.primary.foreground,
    "quickInputList.hoverBackground": alpha(color.interaction.hover, 0.5),
    "quickInputTitle.background": color.canvas.overlay,
    "listFilterWidget.shadow": alpha(color.canvas.inset, 0.5),
    "toolbar.hoverBackground": alpha(color.interaction.hover, 0.5),
    "toolbar.hoverOutline": TRANSPARENT,
    "toolbar.activeBackground": color.interaction.pressed,
    "actionBar.toggledBackground": alpha(color.interaction.selected, 0.5),

    // Status bar
    "statusBar.foreground": color.foreground.muted,
    "statusBar.background": color.canvas.default,
    "statusBar.border": color.border.default,
    "statusBar.focusBorder": alpha(color.accent.primary.background, 0.5),
    "statusBar.noFolderBackground": color.canvas.default,
    "statusBar.debuggingForeground": color.control.primary.foreground,
    "statusBar.debuggingBackground": color.control.primary.background,
    "statusBar.debuggingBorder": color.border.default,
    "statusBarItem.prominentBackground": color.canvas.overlay,
    "statusBarItem.prominentForeground": color.foreground.emphasis,
    "statusBarItem.prominentHoverBackground": chroma
      .mix(color.canvas.overlay, color.interaction.hover, 0.5, "rgb")
      .hex(),
    "statusBarItem.prominentHoverForeground": color.foreground.emphasis,
    "statusBarItem.remoteForeground": color.foreground.default,
    "statusBarItem.remoteBackground": color.canvas.overlay,
    "statusBarItem.hoverBackground": alpha(color.interaction.hover, 0.5),
    "statusBarItem.hoverForeground": color.foreground.emphasis,
    "statusBarItem.activeBackground": color.interaction.pressed,
    "statusBarItem.focusBorder": color.accent.secondary.background,
    "statusBarItem.remoteHoverBackground": alpha(color.interaction.hover, 0.5),
    "statusBarItem.remoteHoverForeground": color.foreground.emphasis,
    "statusBarItem.errorBackground": color.danger.emphasis,
    "statusBarItem.errorForeground": color.foreground.onEmphasis,
    "statusBarItem.errorHoverBackground": color.danger.foreground,
    "statusBarItem.errorHoverForeground": color.foreground.onEmphasis,
    "statusBarItem.warningBackground": color.attention.emphasis,
    "statusBarItem.warningForeground": color.foreground.onEmphasis,
    "statusBarItem.warningHoverBackground": color.attention.foreground,
    "statusBarItem.warningHoverForeground": color.foreground.onEmphasis,
    "statusBarItem.compactHoverBackground": alpha(color.interaction.hover, 0.5),
    "statusBarItem.offlineBackground": color.canvas.overlay,
    "statusBarItem.offlineForeground": color.foreground.muted,
    "statusBarItem.offlineHoverBackground": alpha(color.interaction.hover, 0.5),
    "statusBarItem.offlineHoverForeground": color.foreground.emphasis,
    "statusBar.noFolderBorder": color.border.default,
    "statusBar.noFolderForeground": color.foreground.muted,

    // Editor groups, tabs, and breadcrumbs
    "editorGroupHeader.tabsBackground": color.canvas.inset,
    "editorGroupHeader.tabsBorder": TRANSPARENT,
    "editorGroup.border": color.border.default,
    "tab.activeForeground": color.foreground.emphasis,
    "tab.inactiveForeground": color.foreground.muted,
    "tab.selectedForeground": color.foreground.emphasis,
    "tab.inactiveBackground": color.canvas.inset,
    "tab.activeBackground": color.canvas.default,
    "tab.selectedBackground": alpha(
      alpha(color.interaction.selected, 0.5),
      0.5,
    ),
    "tab.hoverBackground": alpha(color.interaction.hover, 0.5),
    "tab.hoverForeground": color.foreground.emphasis,
    "tab.border": TRANSPARENT,
    "tab.activeBorder": TRANSPARENT,
    "tab.activeBorderTop": color.accent.secondary.background,
    "tab.selectedBorderTop": color.accent.secondary.background,
    "tab.lastPinnedBorder": color.accent.secondary.background,
    "tab.activeModifiedBorder": TRANSPARENT,
    "tab.inactiveModifiedBorder": TRANSPARENT,
    "tab.unfocusedActiveBackground": alpha(
      color.interaction.selectedInactive,
      0.5,
    ),
    "tab.unfocusedActiveForeground": color.foreground.emphasis,
    "tab.unfocusedActiveModifiedBorder": TRANSPARENT,
    "tab.unfocusedHoverBackground": alpha(color.interaction.hover, 0.5),
    "tab.unfocusedHoverForeground": color.foreground.emphasis,
    "tab.unfocusedHoverBorder": TRANSPARENT,
    "tab.unfocusedInactiveBackground": color.canvas.default,
    "tab.unfocusedInactiveForeground": color.foreground.muted,
    "tab.unfocusedInactiveModifiedBorder": TRANSPARENT,
    "tab.unfocusedActiveBorder": TRANSPARENT,
    "tab.unfocusedActiveBorderTop": TRANSPARENT,
    "breadcrumb.foreground": color.foreground.default,
    "breadcrumb.focusForeground": color.foreground.default,
    "breadcrumb.activeSelectionForeground": color.foreground.emphasis,
    "breadcrumbPicker.background": color.canvas.default,
    "breadcrumb.background": color.canvas.default,
    "editorGroup.dropBackground": alpha(color.canvas.inset, 0.8),
    "editorGroup.emptyBackground": color.canvas.default,
    "editorGroup.focusedEmptyBorder": color.border.default,
    "editorGroupHeader.noTabsBackground": color.canvas.default,
    "editorGroupHeader.border": TRANSPARENT,
    "editorGroup.dropIntoPromptForeground": color.foreground.onEmphasis,
    "editorGroup.dropIntoPromptBackground": color.accent.primary.background,
    "editorGroup.dropIntoPromptBorder": color.accent.secondary.background,
    "sideBySideEditor.horizontalBorder": color.border.default,
    "sideBySideEditor.verticalBorder": color.border.default,

    // Editor canvas, selection, and guides
    "editor.foreground": color.foreground.prominent,
    "editor.background": color.canvas.default,
    "editor.foldBackground": alpha(color.canvas.overlay, 0.1),
    "editor.lineHighlightBackground": alpha(color.interaction.highlighted, 0.5),
    "editor.lineHighlightBorder": alpha(color.canvas.raised, 0),
    "editorLineNumber.foreground": color.foreground.subtle,
    "editorLineNumber.activeForeground": color.foreground.emphasis,
    "editorLineNumber.dimmedForeground": color.foreground.subtle,
    "editor.placeholder.foreground": color.foreground.muted,
    "editor.compositionBorder": color.accent.secondary.background,
    "editorUnicodeHighlight.background": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editorUnicodeHighlight.border": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editorWhitespace.foreground": color.foreground.subtle,
    "editorCursor.foreground": color.foreground.emphasis,
    "editor.findMatchBackground": color.accent.primary.background,
    "editor.findMatchForeground": color.foreground.onEmphasis,
    "editor.findMatchHighlightBackground": color.accent.primary.background,
    "editor.findMatchHighlightForeground": color.accent.primary.foreground,
    "editor.linkedEditingBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.inactiveSelectionBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.selectionForeground": color.accent.primary.background,
    "editor.selectionBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.selectionHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.selectionHighlightBorder": TRANSPARENT,
    "editor.wordHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.wordHighlightBorder": TRANSPARENT,
    "editor.wordHighlightStrongBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.wordHighlightStrongBorder": TRANSPARENT,
    "editorBracketMatch.background": alpha(color.canvas.overlay, 0),
    "editorBracketMatch.border": color.accent.secondary.background,
    "editorInlayHint.foreground": color.foreground.muted,
    "editorInlayHint.background": alpha(color.canvas.overlay, 0),
    "editorInlayHint.parameterForeground": color.inlayHint.parameter.foreground,
    "editorInlayHint.parameterBackground": color.inlayHint.parameter.background,
    "editorInlayHint.typeForeground": color.inlayHint.type.foreground,
    "editorInlayHint.typeBackground": color.inlayHint.type.background,
    "editor.findMatchBorder": alpha(color.accent.secondary.background, 0.125),
    "editor.findRangeHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.hoverHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.rangeHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.rangeHighlightBorder": alpha(color.accent.primary.background, 0.5),
    "editor.symbolHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.symbolHighlightBorder": alpha(color.accent.primary.background, 0.5),
    "editor.snippetFinalTabstopHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.snippetFinalTabstopHighlightBorder": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.snippetTabstopHighlightBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.snippetTabstopHighlightBorder": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.wordHighlightTextBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "editor.wordHighlightTextBorder": TRANSPARENT,
    "editorCursor.background": color.attention.foreground,
    "editorIndentGuide.activeBackground1": color.foreground.default,
    "editorIndentGuide.background1": color.border.muted,
    "editorStickyScroll.background": color.canvas.default,
    "editorStickyScrollHover.background": alpha(
      color.accent.secondary.background,
      0.4,
    ),
    "editorStickyScroll.border": alpha(color.border.subtle, 0.5),
    "editorStickyScroll.shadow": alpha(color.canvas.inset, 0.5),
    "editorStickyScrollGutter.background": color.canvas.default,
    "editorGhostText.foreground": color.foreground.emphasis,
    "editorBracketHighlight.foreground1": color.brackets.one,
    "editorBracketHighlight.foreground2": color.brackets.two,
    "editorBracketHighlight.foreground3": color.brackets.three,
    "editorBracketHighlight.foreground4": color.brackets.four,
    "editorBracketHighlight.foreground5": color.brackets.five,
    "editorBracketHighlight.foreground6": color.brackets.six,
    "editorBracketHighlight.unexpectedBracket.foreground":
      color.danger.foreground,

    // Editor diagnostics, rulers, and widgets
    "editorWidget.background": color.canvas.overlay,
    "editorCodeLens.foreground": color.foreground.default,
    "editorError.foreground": color.danger.foreground,
    "editorError.border": color.danger.foreground,
    "editorError.background": alpha(color.danger.muted, 0.2),
    "editorHint.foreground": color.accent.primary.background,
    "editorHint.border": color.accent.secondary.background,
    "editorHint.background": alpha(color.accent.primary.background, 0.2),
    "editorHoverWidget.foreground": color.foreground.emphasis,
    "editorHoverWidget.background": color.canvas.overlay,
    "editorHoverWidget.border": color.border.emphasis,
    "editorHoverWidget.highlightForeground": color.foreground.prominent,
    "editorHoverWidget.statusBarBackground": color.canvas.overlay,
    "editorInfo.foreground": color.info.foreground,
    "editorInfo.border": color.info.foreground,
    "editorInfo.background": alpha(color.info.muted, 0.2),
    "editorLink.activeForeground": color.foreground.default,
    "editorMarkerNavigation.background": color.canvas.default,
    "editorMarkerNavigationError.background": alpha(color.danger.muted, 0.4),
    "editorMarkerNavigationInfo.background": alpha(color.info.muted, 0.4),
    "editorMarkerNavigationWarning.background": alpha(
      color.attention.muted,
      0.4,
    ),
    "editorPane.background": color.canvas.default,
    "editorRuler.foreground": color.canvas.inset,
    "editorSuggestWidget.foreground": color.foreground.emphasis,
    "editorSuggestWidget.background": color.canvas.overlay,
    "editorSuggestWidget.border": color.border.muted,
    "editorSuggestWidget.highlightForeground": color.foreground.default,
    "editorSuggestWidget.focusHighlightForeground": color.foreground.emphasis,
    "editorSuggestWidget.selectedForeground": color.foreground.prominent,
    "editorSuggestWidget.selectedIconForeground": color.foreground.emphasis,
    "editorSuggestWidget.selectedBackground": alpha(
      color.interaction.selected,
      0.5,
    ),
    "editorUnnecessaryCode.opacity": alpha(color.foreground.emphasis, 0.8),
    "editorWarning.foreground": color.attention.foreground,
    "editorWarning.border": color.attention.foreground,
    "editorWarning.background": alpha(color.attention.muted, 0.2),
    "editorWidget.foreground": color.foreground.emphasis,
    "editorWidget.border": color.border.default,
    "editorWidget.resizeBorder": color.border.default,
    "searchEditor.findMatchBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "searchEditor.findMatchBorder": color.border.default,
    "notebook.symbolHighlightBackground": alpha(color.canvas.overlay, 0.4),
    "editorCommentsWidget.rangeBackground": alpha(
      color.accent.tertiary.background,
      0.4,
    ),
    "editorCommentsWidget.rangeActiveBackground": alpha(
      color.accent.tertiary.background,
      0.4,
    ),

    // Source control, diffs, and scrolling
    "editorGutter.modifiedBackground": alpha(color.sourceControl.modified, 0.6),
    "editorGutter.addedBackground": alpha(color.sourceControl.added, 0.6),
    "editorGutter.deletedBackground": alpha(color.sourceControl.deleted, 0.6),
    "diffEditor.insertedLineBackground": alpha(color.sourceControl.added, 0.15),
    "diffEditor.insertedTextBackground": alpha(color.sourceControl.added, 0.1),
    "diffEditor.insertedTextBorder": alpha(color.sourceControl.added, 0),
    "diffEditor.removedLineBackground": alpha(
      color.sourceControl.deleted,
      0.15,
    ),
    "diffEditor.removedTextBackground": alpha(color.sourceControl.deleted, 0.1),
    "diffEditor.removedTextBorder": alpha(color.sourceControl.deleted, 0),
    "diffEditor.diagonalFill": color.border.muted,
    "diffEditor.unchangedRegionBackground": color.canvas.inset,
    "diffEditor.unchangedRegionForeground": color.foreground.muted,
    "diffEditor.unchangedRegionShadow": color.canvas.default,
    "diffEditor.unchangedCodeBackground": color.canvas.inset,
    "diffEditor.move.border": color.accent.tertiary.background,
    "diffEditor.moveActive.border": color.accent.secondary.background,
    "diffEditorGutter.insertedLineBackground": color.sourceControl.added,
    "diffEditorGutter.removedLineBackground": color.sourceControl.deleted,
    "diffEditorOverview.insertedForeground": color.sourceControl.added,
    "diffEditorOverview.removedForeground": color.sourceControl.deleted,
    "multiDiffEditor.headerBackground": color.canvas.inset,
    "multiDiffEditor.background": color.canvas.default,
    "multiDiffEditor.border": color.border.muted,
    "scrollbar.background": alpha(color.canvas.default, 0),
    "scrollbar.shadow": color.canvas.default,
    "scrollbarSlider.background": alpha(color.canvas.raised, 0.6),
    "scrollbarSlider.hoverBackground": alpha(color.canvas.raised, 0.7),
    "scrollbarSlider.activeBackground": alpha(color.canvas.raised, 0.6),
    "editorOverviewRuler.border": alpha(color.border.subtle, 0.5),
    "minimapSlider.background": alpha(color.canvas.raised, 0.4),
    "minimapSlider.hoverBackground": alpha(color.canvas.raised, 0.5),
    "minimapSlider.activeBackground": alpha(color.canvas.raised, 0.4),
    "minimap.background": alpha(color.canvas.default, 0),
    "minimap.foregroundOpacity": alpha(color.foreground.default, 0.86),
    "diffEditor.border": color.canvas.default,
    "editorGutter.background": color.canvas.default,
    "editorGutter.commentRangeForeground": color.foreground.muted,
    "editorGutter.foldingControlForeground": color.foreground.subtle,
    "editorOverviewRuler.addedForeground": color.sourceControl.added,
    "editorOverviewRuler.bracketMatchForeground":
      color.accent.primary.background,
    "editorOverviewRuler.commonContentForeground": color.foreground.default,
    "editorOverviewRuler.currentContentForeground":
      color.accent.tertiary.background,
    "editorOverviewRuler.deletedForeground": color.sourceControl.deleted,
    "editorOverviewRuler.errorForeground": color.danger.foreground,
    "editorOverviewRuler.findMatchForeground": alpha(
      color.foreground.default,
      0.6,
    ),
    "editorOverviewRuler.incomingContentForeground": color.success.foreground,
    "editorOverviewRuler.infoForeground": color.info.foreground,
    "editorOverviewRuler.modifiedForeground": color.sourceControl.modified,
    "editorOverviewRuler.rangeHighlightForeground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "editorOverviewRuler.selectionHighlightForeground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "editorOverviewRuler.warningForeground": color.attention.foreground,
    "editorOverviewRuler.wordHighlightForeground": alpha(
      color.accent.primary.background,
      0.6,
    ),
    "editorOverviewRuler.wordHighlightStrongForeground": alpha(
      color.accent.primary.background,
      0.6,
    ),
    "editorOverviewRuler.wordHighlightTextForeground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "editorOverviewRuler.inlineChatInserted": color.sourceControl.added,
    "editorOverviewRuler.inlineChatRemoved": color.sourceControl.deleted,
    "editorOverviewRuler.commentForeground": color.foreground.subtle,
    "editorOverviewRuler.commentUnresolvedForeground":
      color.accent.primary.background,
    "editorCommentsWidget.resolvedBorder": color.border.muted,
    "editorCommentsWidget.unresolvedBorder": color.accent.secondary.background,
    "editorCommentsWidget.replyInputBackground": color.canvas.overlay,
    "merge.border": color.border.default,
    "merge.commonContentBackground": alpha(color.canvas.inset, 0.1),
    "merge.commonHeaderBackground": alpha(color.canvas.inset, 0.2),
    "merge.currentContentBackground": alpha(
      color.accent.primary.background,
      0.2,
    ),
    "merge.currentHeaderBackground": alpha(
      color.accent.tertiary.background,
      0.2,
    ),
    "merge.incomingContentBackground": alpha(color.success.muted, 0.1),
    "merge.incomingHeaderBackground": alpha(color.success.muted, 0.2),
    "mergeEditor.change.background": alpha(
      color.accent.primary.background,
      0.2,
    ),
    "mergeEditor.change.word.background": alpha(
      color.accent.primary.background,
      0.35,
    ),
    "mergeEditor.conflict.unhandledUnfocused.border": color.danger.muted,
    "mergeEditor.conflict.unhandledFocused.border": color.danger.foreground,
    "mergeEditor.conflict.handledUnfocused.border": color.success.muted,
    "mergeEditor.conflict.handledFocused.border": color.success.foreground,
    "mergeEditor.conflict.handled.minimapOverViewRuler":
      color.success.foreground,
    "mergeEditor.conflict.unhandled.minimapOverViewRuler":
      color.danger.foreground,
    "mergeEditor.conflictingLines.background": color.canvas.overlay,
    "mergeEditor.changeBase.background": alpha(color.foreground.muted, 0.15),
    "mergeEditor.changeBase.word.background": alpha(
      color.foreground.muted,
      0.25,
    ),
    "mergeEditor.conflict.input1.background": alpha(color.danger.muted, 0.2),
    "mergeEditor.conflict.input2.background": alpha(color.success.muted, 0.2),
    "minimap.findMatchHighlight": alpha(color.canvas.overlay, 0.4),
    "minimap.selectionHighlight": alpha(color.accent.secondary.background, 0.4),
    "minimap.selectionOccurrenceHighlight": alpha(
      color.accent.secondary.background,
      0.4,
    ),
    "minimap.errorHighlight": color.danger.foreground,
    "minimap.warningHighlight": color.attention.foreground,
    "minimap.infoHighlight": color.info.foreground,
    "minimap.chatEditHighlight": color.accent.tertiary.background,
    "minimapGutter.addedBackground": color.sourceControl.added,
    "minimapGutter.modifiedBackground": color.sourceControl.modified,
    "minimapGutter.deletedBackground": color.sourceControl.deleted,
    "editorMinimap.inlineChatInserted": color.sourceControl.added,

    // Panels and output views
    "panel.background": color.canvas.inset,
    "panel.border": color.border.muted,
    "panel.dropBorder": color.accent.secondary.background,
    "panelTitle.activeBorder": color.accent.secondary.background,
    "panelTitle.activeForeground": color.foreground.emphasis,
    "panelTitle.inactiveForeground": color.foreground.default,
    "panelTitle.border": color.border.muted,
    "panelTitleBadge.background": color.badge.background,
    "panelTitleBadge.foreground": color.badge.foreground,
    "panelInput.border": color.border.muted,
    "panelSection.border": color.border.muted,
    "panelSection.dropBackground": alpha(color.canvas.inset, 0.8),
    "panelSectionHeader.background": color.canvas.inset,
    "panelSectionHeader.foreground": color.foreground.muted,
    "panelSectionHeader.border": TRANSPARENT,
    "panelStickyScroll.background": color.canvas.inset,
    "panelStickyScroll.border": alpha(color.border.subtle, 0.5),
    "panelStickyScroll.shadow": alpha(color.canvas.inset, 0.5),
    "outputView.background": color.canvas.inset,
    "outputViewStickyScroll.background": color.canvas.inset,

    // Debug controls and console
    "debugIcon.breakpointForeground": color.danger.foreground,
    "debugIcon.breakpointDisabledForeground": color.foreground.subtle,
    "debugIcon.breakpointUnverifiedForeground": color.attention.foreground,
    "debugIcon.breakpointCurrentStackframeForeground":
      color.accent.primary.background,
    "debugIcon.breakpointStackframeForeground": color.accent.primary.background,
    "debugIcon.startForeground": color.success.foreground,
    "debugIcon.pauseForeground": color.attention.foreground,
    "debugIcon.stopForeground": color.danger.foreground,
    "debugIcon.disconnectForeground": color.danger.foreground,
    "debugIcon.restartForeground": color.success.foreground,
    "debugIcon.stepOverForeground": color.accent.primary.background,
    "debugIcon.stepIntoForeground": color.accent.primary.background,
    "debugIcon.stepOutForeground": color.accent.primary.background,
    "debugIcon.continueForeground": color.success.foreground,
    "debugIcon.stepBackForeground": color.accent.primary.background,
    "debugView.exceptionLabelForeground": color.foreground.onEmphasis,
    "debugView.exceptionLabelBackground": color.danger.emphasis,
    "debugView.stateLabelForeground": color.foreground.onEmphasis,
    "debugView.stateLabelBackground": color.accent.primary.background,
    "debugView.valueChangedHighlight": color.attention.foreground,
    "editor.inlineValuesForeground": color.foreground.muted,
    "editor.inlineValuesBackground": alpha(color.canvas.overlay, 0.6),
    "debugConsole.infoForeground": color.info.foreground,
    "debugConsole.warningForeground": color.attention.foreground,
    "debugConsole.errorForeground": color.danger.foreground,
    "debugConsole.sourceForeground": color.foreground.subtle,
    "debugConsoleInputIcon.foreground": color.accent.primary.background,
    "debugTokenExpression.name": color.accent.tertiary.background,
    "debugTokenExpression.value": color.accent.primary.background,
    "debugTokenExpression.string": color.accent.primary.background,
    "debugTokenExpression.boolean": color.success.foreground,
    "debugTokenExpression.number": color.success.foreground,
    "debugTokenExpression.error": color.danger.foreground,
    "debugExceptionWidget.background": color.canvas.default,
    "debugExceptionWidget.border": color.border.muted,

    // Testing
    "testing.iconFailed": color.danger.foreground,
    "testing.iconErrored": color.danger.foreground,
    "testing.iconPassed": color.success.foreground,
    "testing.iconQueued": color.foreground.default,
    "testing.iconUnset": color.foreground.muted,
    "testing.iconSkipped": color.attention.foreground,
    "testing.iconErrored.retired": color.danger.muted,
    "testing.iconFailed.retired": color.danger.muted,
    "testing.iconPassed.retired": color.success.muted,
    "testing.iconQueued.retired": color.foreground.subtle,
    "testing.iconUnset.retired": color.foreground.subtle,
    "testing.iconSkipped.retired": color.attention.muted,
    "testing.runAction": color.success.emphasis,
    "testing.peekBorder": color.border.muted,
    "testing.peekHeaderBackground": color.canvas.default,
    "testing.message.info.decorationForeground": color.info.foreground,
    "testing.message.error.lineBackground": alpha(color.danger.muted, 0.2),
    "testing.message.info.lineBackground": alpha(color.info.muted, 0.2),
    "testing.messagePeekBorder": color.border.muted,
    "testing.messagePeekHeaderBackground": color.canvas.default,
    "testing.coveredBackground": alpha(color.success.muted, 0.2),
    "testing.coveredBorder": color.success.foreground,
    "testing.coveredGutterBackground": color.success.foreground,
    "testing.uncoveredBranchBackground": alpha(color.attention.muted, 0.2),
    "testing.uncoveredBackground": alpha(color.danger.muted, 0.2),
    "testing.uncoveredBorder": color.danger.foreground,
    "testing.uncoveredGutterBackground": color.danger.foreground,
    "testing.coverCountBadgeBackground": color.canvas.overlay,
    "testing.coverCountBadgeForeground": color.foreground.emphasis,
    "testing.message.error.badgeBackground": color.danger.emphasis,
    "testing.message.error.badgeBorder": color.danger.foreground,
    "testing.message.error.badgeForeground": color.foreground.onEmphasis,
    "ports.iconRunningProcessForeground": color.success.foreground,

    // Notebooks
    "notebook.editorBackground": color.canvas.default,
    "notebook.cellBorderColor": color.border.muted,
    "notebook.cellHoverBackground": alpha(color.interaction.hover, 0.5),
    "notebook.cellInsertionIndicator": color.accent.primary.background,
    "notebook.cellStatusBarItemHoverBackground": alpha(
      color.interaction.hover,
      0.5,
    ),
    "notebook.cellToolbarSeparator": color.border.muted,
    "notebook.cellEditorBackground": color.canvas.default,
    "notebook.focusedCellBackground": alpha(color.interaction.focused, 0.5),
    "notebook.focusedCellBorder": color.accent.secondary.background,
    "notebook.focusedEditorBorder": color.accent.secondary.background,
    "notebook.inactiveFocusedCellBorder": color.border.muted,
    "notebook.inactiveSelectedCellBorder": color.border.muted,
    "notebook.outputContainerBackgroundColor": color.canvas.inset,
    "notebook.outputContainerBorderColor": color.border.muted,
    "notebook.selectedCellBackground": alpha(color.interaction.selected, 0.5),
    "notebook.selectedCellBorder": color.accent.secondary.background,
    "notebookScrollbarSlider.activeBackground": color.canvas.raised,
    "notebookScrollbarSlider.background": alpha(color.canvas.raised, 0.25),
    "notebookScrollbarSlider.hoverBackground": alpha(color.canvas.raised, 0.5),
    "notebookStatusErrorIcon.foreground": color.danger.foreground,
    "notebookStatusRunningIcon.foreground": color.accent.primary.background,
    "notebookStatusSuccessIcon.foreground": color.success.foreground,
    "notebookEditorOverviewRuler.runningCellForeground":
      color.accent.primary.background,

    // Gauges and charts
    "gauge.foreground": color.info.foreground,
    "gauge.background": alpha(color.info.muted, 0.3),
    "gauge.border": color.border.default,
    "gauge.warningForeground": color.attention.foreground,
    "gauge.warningBackground": alpha(color.attention.muted, 0.3),
    "gauge.errorForeground": color.danger.foreground,
    "gauge.errorBackground": alpha(color.danger.muted, 0.3),
    "charts.foreground": color.foreground.default,
    "charts.lines": alpha(color.foreground.default, 0.5),
    "charts.blue": color.accent.tertiary.background,
    "charts.red": color.danger.foreground,
    "charts.yellow": color.attention.foreground,
    "charts.orange": color.attention.muted,
    "charts.green": color.success.foreground,
    "charts.purple": color.accent.primary.background,

    // Outline and symbol icons
    "symbolIcon.arrayForeground": color.attention.muted,
    "symbolIcon.booleanForeground": color.accent.tertiary.background,
    "symbolIcon.classForeground": color.attention.muted,
    "symbolIcon.colorForeground": color.accent.primary.background,
    "symbolIcon.constructorForeground": color.accent.primary.background,
    "symbolIcon.enumeratorForeground": color.attention.muted,
    "symbolIcon.enumeratorMemberForeground": color.accent.tertiary.background,
    "symbolIcon.eventForeground": color.foreground.subtle,
    "symbolIcon.fieldForeground": color.attention.muted,
    "symbolIcon.fileForeground": color.attention.muted,
    "symbolIcon.folderForeground": color.attention.muted,
    "symbolIcon.functionForeground": color.accent.primary.background,
    "symbolIcon.interfaceForeground": color.attention.muted,
    "symbolIcon.keyForeground": color.accent.tertiary.background,
    "symbolIcon.keywordForeground": color.syntax.keyword,
    "symbolIcon.methodForeground": color.accent.primary.background,
    "symbolIcon.moduleForeground": color.syntax.type,
    "symbolIcon.namespaceForeground": color.syntax.type,
    "symbolIcon.nullForeground": color.accent.tertiary.background,
    "symbolIcon.numberForeground": color.success.foreground,
    "symbolIcon.objectForeground": color.attention.muted,
    "symbolIcon.operatorForeground": color.accent.primary.background,
    "symbolIcon.packageForeground": color.attention.muted,
    "symbolIcon.propertyForeground": color.attention.muted,
    "symbolIcon.referenceForeground": color.accent.tertiary.background,
    "symbolIcon.snippetForeground": color.accent.tertiary.background,
    "symbolIcon.stringForeground": color.accent.primary.background,
    "symbolIcon.structForeground": color.attention.muted,
    "symbolIcon.textForeground": color.accent.primary.background,
    "symbolIcon.typeParameterForeground": color.accent.primary.background,
    "symbolIcon.unitForeground": color.accent.tertiary.background,
    "symbolIcon.variableForeground": color.attention.muted,
    "symbolIcon.constantForeground": color.success.foreground,

    // Integrated terminal
    "terminal.foreground": color.foreground.emphasis,
    "terminal.ansiBlack": color.ansi.black,
    "terminal.ansiRed": color.ansi.red,
    "terminal.ansiGreen": color.ansi.green,
    "terminal.ansiYellow": color.ansi.yellow,
    "terminal.ansiBlue": color.ansi.blue,
    "terminal.ansiMagenta": color.ansi.magenta,
    "terminal.ansiCyan": color.ansi.cyan,
    "terminal.ansiWhite": color.ansi.white,
    "terminal.ansiBrightBlack": color.ansi.brightBlack,
    "terminal.ansiBrightRed": color.ansi.brightRed,
    "terminal.ansiBrightGreen": color.ansi.brightGreen,
    "terminal.ansiBrightYellow": color.ansi.brightYellow,
    "terminal.ansiBrightBlue": color.ansi.brightBlue,
    "terminal.ansiBrightMagenta": color.ansi.brightMagenta,
    "terminal.ansiBrightCyan": color.ansi.brightCyan,
    "terminal.ansiBrightWhite": color.ansi.brightWhite,
    "terminal.background": color.canvas.inset,
    "terminal.border": color.border.muted,
    "terminal.findMatchBackground": alpha(
      color.accent.secondary.background,
      0.5,
    ),
    "terminal.findMatchBorder": color.border.default,
    "terminal.findMatchHighlightBackground": alpha(
      color.accent.secondary.background,
      0.5,
    ),
    "terminal.findMatchHighlightBorder": color.border.default,
    "terminal.hoverHighlightBackground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "terminal.selectionBackground": alpha(color.accent.primary.background, 0.5),
    "terminal.selectionForeground": color.foreground.onEmphasis,
    "terminal.inactiveSelectionBackground": alpha(
      color.accent.secondary.background,
      0.125,
    ),
    "terminal.tab.activeBorder": color.accent.secondary.background,
    "terminalCursor.background": color.canvas.inset,
    "terminalCursor.foreground": color.foreground.emphasis,
    "terminal.dropBackground": alpha(color.canvas.inset, 0.8),
    "terminalCommandDecoration.defaultBackground": color.border.muted,
    "terminalCommandDecoration.successBackground": color.success.foreground,
    "terminalCommandDecoration.errorBackground": color.danger.foreground,
    "terminalOverviewRuler.cursorForeground": color.accent.primary.background,
    "terminalOverviewRuler.findMatchForeground":
      color.accent.primary.background,
    "terminalStickyScroll.background": color.canvas.inset,
    "terminalStickyScroll.border": color.border.muted,
    "terminalStickyScrollHover.background": color.canvas.overlay,
    "terminal.initialHintForeground": color.foreground.subtle,
    "terminalOverviewRuler.border": color.border.muted,
    "terminalCommandGuide.foreground": color.foreground.subtle,

    // Bracket pairs
    "editorBracketPairGuide.activeBackground1": alpha(color.brackets.one, 0.75),
    "editorBracketPairGuide.activeBackground2": alpha(color.brackets.two, 0.75),
    "editorBracketPairGuide.activeBackground3": alpha(
      color.brackets.three,
      0.75,
    ),
    "editorBracketPairGuide.activeBackground4": alpha(
      color.brackets.four,
      0.75,
    ),
    "editorBracketPairGuide.activeBackground5": alpha(
      color.brackets.five,
      0.75,
    ),
    "editorBracketPairGuide.activeBackground6": alpha(color.brackets.six, 0.75),
    "editorBracketPairGuide.background1": alpha(color.brackets.one, 0.5),
    "editorBracketPairGuide.background2": alpha(color.brackets.two, 0.5),
    "editorBracketPairGuide.background3": alpha(color.brackets.three, 0.5),
    "editorBracketPairGuide.background4": alpha(color.brackets.four, 0.5),
    "editorBracketPairGuide.background5": alpha(color.brackets.five, 0.5),
    "editorBracketPairGuide.background6": alpha(color.brackets.six, 0.5),

    // Source control decorations
    "gitDecoration.addedResourceForeground": color.sourceControl.added,
    "gitDecoration.modifiedResourceForeground": color.sourceControl.modified,
    "gitDecoration.renamedResourceForeground": color.sourceControl.renamed,
    "gitDecoration.deletedResourceForeground": color.sourceControl.deleted,
    "gitDecoration.untrackedResourceForeground": color.sourceControl.untracked,
    "gitDecoration.ignoredResourceForeground": alpha(
      color.sourceControl.ignored,
      0.5,
    ),
    "gitDecoration.conflictingResourceForeground":
      color.sourceControl.conflicting,
    "gitDecoration.stageModifiedResourceForeground":
      color.sourceControl.stageModified,
    "gitDecoration.stageDeletedResourceForeground":
      color.sourceControl.stageDeleted,
    "gitDecoration.submoduleResourceForeground": color.sourceControl.submodule,
    "git.blame.editorDecorationForeground": color.foreground.subtle,
    "scmGraph.historyItemHoverLabelForeground": color.foreground.onEmphasis,
    "scmGraph.foreground1": color.accent.primary.background,
    "scmGraph.foreground2": color.accent.primary.background,
    "scmGraph.foreground3": color.accent.tertiary.background,
    "scmGraph.foreground4": color.success.foreground,
    "scmGraph.foreground5": color.attention.foreground,
    "scmGraph.historyItemHoverAdditionsForeground": color.success.foreground,
    "scmGraph.historyItemHoverDeletionsForeground": color.danger.foreground,
    "scmGraph.historyItemRefColor": color.accent.primary.background,
    "scmGraph.historyItemRemoteRefColor": color.info.foreground,
    "scmGraph.historyItemBaseRefColor": color.foreground.muted,
    "scmGraph.historyItemHoverDefaultLabelForeground":
      color.foreground.emphasis,
    "scmGraph.historyItemHoverDefaultLabelBackground": color.canvas.overlay,

    // Debugging and peek views
    "debugToolBar.background": color.canvas.default,
    "editor.stackFrameHighlightBackground": alpha(
      color.interaction.highlighted,
      0.5,
    ),
    "editor.focusedStackFrameHighlightBackground": alpha(
      color.interaction.focused,
      0.5,
    ),
    "peekViewEditor.matchHighlightBackground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "peekViewResult.matchHighlightBackground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "peekViewEditor.background": color.canvas.inset,
    "peekViewResult.background": color.canvas.inset,
    "debugToolBar.border": color.border.muted,
    "peekView.border": color.accent.secondary.background,
    "peekViewEditor.matchHighlightBorder": alpha(
      color.accent.primary.background,
      0.03,
    ),
    "peekViewEditorGutter.background": color.canvas.inset,
    "peekViewResult.fileForeground": color.foreground.muted,
    "peekViewResult.lineForeground": color.foreground.muted,
    "peekViewResult.selectionBackground": alpha(
      color.accent.primary.background,
      0.25,
    ),
    "peekViewResult.selectionForeground": color.foreground.emphasis,
    "peekViewTitle.background": color.canvas.inset,
    "peekViewTitleDescription.foreground": color.foreground.muted,
    "peekViewTitleLabel.foreground": color.foreground.emphasis,

    // Settings and welcome page
    "settings.headerForeground": color.foreground.emphasis,
    "settings.modifiedItemIndicator": color.foreground.default,
    "settings.rowHoverBackground": alpha(color.interaction.hover, 0.5),
    "settings.focusedRowBackground": alpha(color.interaction.focused, 0.5),
    "settings.focusedRowBorder": color.accent.secondary.background,
    "settings.headerBorder": color.border.muted,
    "settings.sashBorder": color.border.muted,
    "settings.settingsHeaderHoverForeground": color.foreground.emphasis,
    "welcomePage.progress.foreground": color.accent.primary.background,
    "welcomePage.tileBackground": color.canvas.overlay,
    "welcomePage.tileHoverBackground": alpha(color.interaction.hover, 0.5),
    "settings.checkboxBackground": color.canvas.overlay,
    "settings.checkboxBorder": color.border.emphasis,
    "settings.checkboxForeground": color.foreground.emphasis,
    "settings.dropdownBackground": color.canvas.overlay,
    "settings.dropdownBorder": color.border.emphasis,
    "settings.dropdownForeground": color.foreground.emphasis,
    "settings.dropdownListBorder": color.border.muted,
    "settings.numberInputBackground": color.canvas.overlay,
    "settings.numberInputBorder": color.border.emphasis,
    "settings.numberInputForeground": color.foreground.emphasis,
    "settings.textInputBackground": color.canvas.overlay,
    "settings.textInputBorder": color.border.emphasis,
    "settings.textInputForeground": color.foreground.emphasis,
    "walkThrough.embeddedEditorBackground": color.canvas.default,
    "welcomePage.background": color.canvas.default,
    "welcomePage.progress.background": color.canvas.overlay,
    "welcomePage.tileBorder": color.border.muted,
    "widget.border": color.border.default,
    "widget.shadow": alpha(color.canvas.inset, 0.5),
    "commentsView.resolvedIcon": color.foreground.subtle,
    "commentsView.unresolvedIcon": color.accent.primary.background,
    "markdownAlert.note.foreground": color.info.foreground,
    "markdownAlert.tip.foreground": color.success.foreground,
    "markdownAlert.important.foreground": color.accent.primary.background,
    "markdownAlert.warning.foreground": color.attention.foreground,
    "markdownAlert.caution.foreground": color.danger.foreground,

    // Chat, agents, and inline editing
    "chat.requestBackground": alpha(color.canvas.overlay, 0),
    "chat.requestBorder": alpha(color.border.emphasis, 0.6),
    "chat.requestBubbleBackground": alpha(color.canvas.overlay, 0.6),
    "chat.requestBubbleHoverBackground": alpha(color.canvas.overlay, 0.6),
    "chat.requestCodeBorder": alpha(color.border.emphasis, 0),
    "chat.slashCommandBackground": color.canvas.overlay,
    "chat.slashCommandForeground": color.foreground.emphasis,
    "chat.avatarBackground": color.canvas.overlay,
    "chat.avatarForeground": color.foreground.emphasis,
    "chat.editedFileForeground": color.sourceControl.modified,
    "chat.linesAddedForeground": alpha(color.sourceControl.added, 0.6),
    "chat.linesRemovedForeground": alpha(color.sourceControl.deleted, 0.6),
    "chat.checkpointSeparator": color.canvas.overlay,
    "chat.thinkingShimmer": alpha(color.accent.primary.background, 0.84),
    "chat.inputWorkingBorderColor1": alpha(
      color.accent.primary.background,
      0.5,
    ),
    "chat.inputWorkingBorderColor2": alpha(
      color.accent.primary.background,
      0.5,
    ),
    "chat.inputWorkingBorderColor3": alpha(
      color.accent.tertiary.background,
      0.5,
    ),
    "chatManagement.sashBorder": color.border.muted,
    "agents.background": color.canvas.default,
    "agentsPanel.background": color.canvas.default,
    "agentsPanel.foreground": color.foreground.default,
    "agentsPanel.border": color.border.muted,
    "agentsCard.border": color.border.muted,
    "agentsBottomPanel.border": color.border.muted,
    "agentsGradient.tintColor": color.accent.primary.background,
    "agentsChatInput.background": color.canvas.overlay,
    "agentsChatInput.foreground": color.foreground.default,
    "agentsChatInput.border": color.border.default,
    "agentsChatInput.focusBorder": color.accent.secondary.background,
    "agentsChatInput.placeholderForeground": color.foreground.subtle,
    "agentsNewSessionButton.background": alpha(color.canvas.default, 0),
    "agentsNewSessionButton.foreground": color.foreground.default,
    "agentsNewSessionButton.border": color.border.default,
    "agentsNewSessionButton.hoverBackground": alpha(
      color.interaction.hover,
      0.5,
    ),
    "activeSessionView.background": color.canvas.overlay,
    "inactiveSessionView.background": color.canvas.inset,
    "activeSessionView.foreground": color.foreground.emphasis,
    "inactiveSessionView.foreground": color.foreground.muted,
    "agentFeedbackEditorWidget.background": color.canvas.overlay,
    "agentFeedbackEditorWidget.border": color.border.muted,
    "agentFeedbackInputWidget.border": color.border.default,
    "agentsUpdateButton.downloadingBackground": color.attention.emphasis,
    "agentsUpdateButton.downloadedBackground": color.success.emphasis,
    "agentsMobileDiff.addedForeground": color.sourceControl.added,
    "agentsMobileDiff.modifiedForeground": color.sourceControl.modified,
    "agentsMobileDiff.deletedForeground": color.sourceControl.deleted,
    "agentsBadge.background": color.accent.primary.background,
    "agentsBadge.foreground": color.accent.primary.foreground,
    "agentsUnreadBadge.background": color.accent.primary.background,
    "agentsUnreadBadge.foreground": color.accent.primary.foreground,
    "agentSessionReadIndicator.foreground": color.accent.primary.background,
    "agentSessionSelectedBadge.border": color.accent.secondary.background,
    "agentSessionSelectedUnfocusedBadge.border": alpha(
      color.accent.primary.background,
      0.5,
    ),
    "agentStatusIndicator.background": color.accent.primary.background,
    "aiCustomizationManagement.sashBorder": color.border.muted,
    "inlineChat.background": color.canvas.default,
    "inlineChat.foreground": color.foreground.default,
    "inlineChat.border": color.border.muted,
    "inlineChat.shadow": alpha(color.canvas.inset, 0.5),
    "inlineChatInput.background": color.canvas.default,
    "inlineChatInput.border": color.border.default,
    "inlineChatInput.focusBorder": color.accent.tertiary.background,
    "inlineChatInput.placeholderForeground": color.foreground.subtle,
    "inlineChatDiff.inserted": alpha(color.sourceControl.added, 0.2),
    "inlineChatDiff.removed": alpha(color.sourceControl.deleted, 0.2),
    "inlineEdit.gutterIndicator.primaryBorder":
      color.accent.secondary.background,
    "inlineEdit.gutterIndicator.primaryForeground": color.foreground.emphasis,
    "inlineEdit.gutterIndicator.primaryBackground": alpha(
      color.accent.primary.background,
      0.2,
    ),
    "inlineEdit.gutterIndicator.secondaryBorder":
      color.accent.primary.background,
    "inlineEdit.gutterIndicator.secondaryForeground": color.foreground.emphasis,
    "inlineEdit.gutterIndicator.secondaryBackground": alpha(
      color.accent.primary.background,
      0.2,
    ),
    "inlineEdit.gutterIndicator.successfulBorder": color.success.foreground,
    "inlineEdit.gutterIndicator.successfulForeground": color.success.foreground,
    "inlineEdit.gutterIndicator.successfulBackground": alpha(
      color.success.muted,
      0.2,
    ),
    "inlineEdit.gutterIndicator.background": color.canvas.overlay,
    "inlineEdit.originalBackground": alpha(color.danger.muted, 0.1),
    "inlineEdit.modifiedBackground": alpha(color.success.muted, 0.1),
    "inlineEdit.originalChangedLineBackground": alpha(color.danger.muted, 0.2),
    "inlineEdit.originalChangedTextBackground": alpha(color.danger.muted, 0.3),
    "inlineEdit.modifiedChangedLineBackground": alpha(color.success.muted, 0.2),
    "inlineEdit.modifiedChangedTextBackground": alpha(color.success.muted, 0.3),
    "inlineEdit.originalBorder": alpha(color.danger.foreground, 0),
    "inlineEdit.modifiedBorder": alpha(color.success.foreground, 0),
    "inlineEdit.tabWillAcceptModifiedBorder": color.success.foreground,
    "inlineEdit.tabWillAcceptOriginalBorder": color.danger.foreground,
    "interactive.activeCodeBorder": color.accent.tertiary.background,
    "interactive.inactiveCodeBorder": color.border.default,
  };
}

module.exports = createWorkbenchColors;
