const chroma = require("chroma-js");

const ansiNames = {
  black: "black",
  red: "red",
  green: "green",
  yellow: "yellow",
  blue: "blue",
  magenta: "magenta",
  cyan: "cyan",
  white: "white",
  brightBlack: "bright_black",
  brightRed: "bright_red",
  brightGreen: "bright_green",
  brightYellow: "bright_yellow",
  brightBlue: "bright_blue",
  brightMagenta: "bright_magenta",
  brightCyan: "bright_cyan",
  brightWhite: "bright_white",
};

const dimAnsiNames = [
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
];

function createTheme(name, color) {
  const syntax = {
    attribute: color.syntax.embedded,
    "attribute.builtin": color.syntax.decorator,
    "attribute.jsx": color.syntax.embedded,
    "attribute.special": color.syntax.property,
    charset: color.syntax.keyword,
    boolean: color.syntax.boolean,
    comment: color.syntax.comment,
    "comment.doc": color.syntax.comment,
    constant: color.syntax.constant,
    "constant.builtin": color.syntax.builtin,
    constructor: color.syntax.class,
    embedded: color.syntax.embedded,
    emphasis: color.foreground.default,
    "emphasis.strong": color.foreground.emphasis,
    enum: color.syntax.type,
    function: color.syntax.function,
    "function.builtin": color.syntax.function,
    "function.call": color.syntax.function,
    "function.decorator": color.syntax.decorator,
    "function.decorator.call": color.syntax.decorator,
    "function.definition": color.syntax.function,
    "function.kwargs": color.syntax.parameter,
    "function.method": color.syntax.method,
    "function.method.call": color.syntax.method,
    "function.method.constructor": color.syntax.method,
    hint: color.foreground.muted,
    keyword: color.syntax.keyword,
    "keyword.control": color.syntax.controlFlow,
    "keyword.declaration": color.syntax.storage,
    "keyword.definition": color.syntax.storage,
    "keyword.import": color.syntax.keyword,
    "keyword.operator": color.syntax.operator,
    "keyword.operator.regex": color.syntax.regexp,
    keyframes: color.syntax.keyword,
    label: color.syntax.controlFlow,
    link_text: color.accent.foreground,
    "link_text.markup": color.accent.foreground,
    link_uri: color.accent.tertiary,
    "link_uri.markup": color.accent.tertiary,
    media: color.syntax.keyword,
    namespace: color.syntax.type,
    number: color.syntax.number,
    operator: color.syntax.operator,
    predictive: color.foreground.subtle,
    preproc: color.syntax.declaration,
    primary: color.foreground.emphasis,
    property: color.syntax.property,
    "property.name": color.syntax.property,
    punctuation: color.syntax.punctuation,
    "punctuation.bracket": color.brackets.one,
    "punctuation.bracket.html": color.syntax.punctuation,
    "punctuation.bracket.jsx": color.syntax.punctuation,
    "punctuation.delimiter": color.syntax.punctuation,
    "punctuation.delimiter.html": color.syntax.punctuation,
    "punctuation.delimiter.jsx": color.syntax.punctuation,
    "punctuation.embedded.markup": color.syntax.punctuation,
    "punctuation.list_marker": color.syntax.punctuation,
    "punctuation.list_marker.markup": color.syntax.punctuation,
    "punctuation.markup": color.syntax.punctuation,
    "punctuation.special": color.syntax.operator,
    "selector.class": color.syntax.class,
    "selector.id": color.syntax.keyword,
    "selector.pseudo": color.syntax.keyword,
    "string.escape": color.syntax.embedded,
    "string.doc": color.syntax.string,
    "string.regex": color.syntax.regexp,
    "string.special": color.syntax.embedded,
    string: color.syntax.string,
    tag: color.syntax.tag,
    "tag.doctype": color.syntax.keyword,
    "tag.jsx": color.syntax.tag,
    "tag.component.jsx": color.syntax.component,
    "text.jsx": color.syntax.children,
    "text.literal": color.foreground.default,
    text: color.foreground.default,
    title: color.foreground.emphasis,
    "title.markup": color.foreground.emphasis,
    type: color.syntax.type,
    "type.builtin": color.syntax.builtin,
    "type.class": color.syntax.class,
    "type.class.builtin": color.syntax.builtin,
    "type.class.call": color.syntax.class,
    "type.class.definition": color.syntax.class,
    "type.class.inheritance": color.syntax.class,
    "type.name": color.syntax.type,
    "type.unit": color.syntax.number,
    variable: color.syntax.variable,
    "variable.parameter": color.syntax.parameter,
    "variable.special": color.syntax.builtin,
    variant: color.syntax.class,
  };

  return {
    name,
    appearance: "dark",
    style: {
      accents: [
        color.brackets.one,
        color.brackets.two,
        color.brackets.three,
        color.brackets.four,
        color.brackets.five,
        color.brackets.six,
      ],
      players: [
        {
          cursor: color.accent.foreground,
          background: color.accent.foreground,
          selection: chroma(color.accent.secondary).alpha(0.24).hex(),
        },
      ],
      background: color.canvas.default,
      "surface.background": color.canvas.default,
      "elevated_surface.background": color.canvas.overlay,
      "panel.background": color.canvas.inset,
      "panel.focused_border": color.accent.foreground,
      "pane.focused_border": color.accent.foreground,
      "pane_group.border": color.border.default,
      "status_bar.background": color.canvas.inset,
      "title_bar.background": color.canvas.inset,
      "title_bar.inactive_background": color.canvas.default,
      "toolbar.background": color.canvas.default,
      "tab_bar.background": color.canvas.inset,
      "tab.active_background": color.canvas.default,
      "tab.inactive_background": color.canvas.inset,
      "editor.background": color.canvas.default,
      "editor.foreground": color.foreground.default,
      "editor.gutter.background": color.canvas.default,
      "editor.subheader.background": color.canvas.inset,
      "editor.line_number": color.foreground.subtle,
      "editor.active_line_number": color.foreground.emphasis,
      "editor.active_line.background": color.canvas.overlay,
      "editor.highlighted_line.background": color.canvas.overlay,
      "editor.invisible": color.foreground.subtle,
      "editor.indent_guide": color.border.muted,
      "editor.indent_guide_active": color.border.emphasis,
      "panel.indent_guide": color.border.muted,
      "panel.indent_guide_active": color.border.emphasis,
      "panel.indent_guide_hover": color.border.emphasis,
      "editor.wrap_guide": color.border.muted,
      "editor.active_wrap_guide": color.border.emphasis,
      "editor.document_highlight.bracket_background": chroma(
        color.accent.secondary,
      )
        .alpha(0.24)
        .hex(),
      "editor.document_highlight.read_background": chroma(
        color.accent.secondary,
      )
        .alpha(0.125)
        .hex(),
      "editor.document_highlight.write_background": chroma(
        color.accent.secondary,
      )
        .alpha(0.24)
        .hex(),
      "search.match_background": chroma(color.accent.subtle).alpha(0.24).hex(),
      "search.active_match_background": chroma(color.accent.subtle)
        .alpha(0.4)
        .hex(),
      border: color.border.default,
      "border.variant": color.border.muted,
      "border.focused": color.accent.foreground,
      "border.selected": color.border.emphasis,
      "border.disabled": color.border.subtle,
      "border.transparent": "#00000000",
      text: color.foreground.default,
      "text.muted": color.foreground.muted,
      "text.accent": color.accent.foreground,
      "text.placeholder": color.foreground.subtle,
      "text.disabled": color.foreground.subtle,
      icon: color.foreground.default,
      "icon.muted": color.foreground.muted,
      "icon.accent": color.accent.foreground,
      "icon.placeholder": color.foreground.subtle,
      "icon.disabled": color.foreground.subtle,
      // Zed reuses element.* for panel rows, so its states track the surface ramp.
      "element.background": color.control.secondary.background,
      "element.hover": color.interaction.hover,
      "element.active": color.interaction.pressed,
      "element.selected": color.interaction.selected,
      "element.disabled": color.canvas.overlay,
      "ghost_element.background": "#00000000",
      "ghost_element.hover": color.interaction.hover,
      "ghost_element.active": color.interaction.pressed,
      "ghost_element.selected": color.interaction.selected,
      "ghost_element.disabled": "#00000000",
      "drop_target.background": chroma(color.accent.secondary)
        .alpha(0.24)
        .hex(),
      "scrollbar.thumb.background": color.border.emphasis,
      "scrollbar.thumb.hover_background": color.foreground.subtle,
      "scrollbar.thumb.border": color.border.default,
      "scrollbar.track.background": color.canvas.default,
      "scrollbar.track.border": color.border.muted,
      "link_text.hover": color.accent.emphasis,
      created: color.sourceControl.added,
      "created.background": chroma(color.sourceControl.added).alpha(0.15).hex(),
      "created.border": "#00000000",
      modified: color.sourceControl.modified,
      "modified.background": chroma(color.sourceControl.modified)
        .alpha(0.15)
        .hex(),
      "modified.border": "#00000000",
      renamed: color.sourceControl.renamed,
      "renamed.background": chroma(color.sourceControl.renamed)
        .alpha(0.15)
        .hex(),
      "renamed.border": "#00000000",
      deleted: color.sourceControl.deleted,
      "deleted.background": chroma(color.sourceControl.deleted)
        .alpha(0.15)
        .hex(),
      "deleted.border": "#00000000",
      ignored: color.sourceControl.ignored,
      "ignored.background": chroma(color.sourceControl.ignored)
        .alpha(0.15)
        .hex(),
      "ignored.border": "#00000000",
      hidden: color.foreground.subtle,
      "hidden.background": chroma(color.foreground.subtle).alpha(0.15).hex(),
      "hidden.border": "#00000000",
      conflict: color.sourceControl.conflicting,
      "conflict.background": chroma(color.sourceControl.conflicting)
        .alpha(0.15)
        .hex(),
      "conflict.border": "#00000000",
      success: color.success.foreground,
      "success.background": chroma(color.success.foreground).alpha(0.1).hex(),
      "success.border": color.border.emphasis,
      warning: color.attention.foreground,
      "warning.background": chroma(color.attention.foreground).alpha(0.1).hex(),
      "warning.border": color.border.emphasis,
      error: color.danger.foreground,
      "error.background": chroma(color.danger.foreground).alpha(0.1).hex(),
      "error.border": color.border.emphasis,
      info: color.info.foreground,
      // Zed drives TintColor::Accent (selected toggles) from the info tint.
      "info.background": chroma(color.accent.foreground).alpha(0.15).hex(),
      "info.border": chroma(color.accent.foreground).alpha(0.4).hex(),
      hint: color.foreground.muted,
      "hint.background": "#00000000",
      "hint.border": "#00000000",
      predictive: color.foreground.subtle,
      "predictive.background": "#00000000",
      "predictive.border": "#00000000",
      unreachable: color.foreground.subtle,
      "unreachable.background": "#00000000",
      "unreachable.border": "#00000000",
      "terminal.background": color.canvas.default,
      "terminal.foreground": color.foreground.default,
      "terminal.bright_foreground": color.foreground.emphasis,
      "terminal.dim_foreground": color.foreground.muted,
      "terminal.ansi.background": color.canvas.default,
      ...Object.fromEntries(
        Object.entries(ansiNames).map(([source, target]) => [
          `terminal.ansi.${target}`,
          color.ansi[source],
        ]),
      ),
      // Zed's dim ANSI slots default to its own palette unless mixed here.
      ...Object.fromEntries(
        dimAnsiNames.map((source) => [
          `terminal.ansi.dim_${source}`,
          chroma.mix(color.ansi[source], color.canvas.default, 0.4).hex(),
        ]),
      ),
      syntax: Object.fromEntries(
        Object.entries(syntax).map(([capture, value]) => [
          capture,
          {
            color: value,
            ...(capture === "comment" || capture === "emphasis"
              ? { font_style: "italic" }
              : {}),
            ...(capture === "emphasis.strong" ? { font_weight: 700 } : {}),
          },
        ]),
      ),
    },
  };
}

module.exports = createTheme;
